# SPDX-License-Identifier: LGPL-2.1-or-later

"""Shared, headless access to SteveCAD's pinned Fasteners workbench.

This adapter owns canonical identity and validation. Geometry remains owned by
the separately distributed GPL Fasteners module.
"""

from __future__ import annotations

import hashlib
import importlib
import json
import math
from pathlib import Path
import re
import sys
from typing import Any, Mapping, Sequence


CATALOG_SCHEMA = "stevecad-fastener-catalog-v1"
COMPONENT_SCHEMA = "stevecad-standard-fastener-v1"
INTERFACE_SCHEMA = "stevecad-standard-component-interfaces-v1"
HOLE_SCHEMA = "stevecad-fastener-hole-v1"
CATALOG_ID = "freecad-fasteners"
PROVENANCE_FILE = "fasteners-provenance.json"
MAX_SEARCH_RESULTS = 100
MAX_SEARCH_QUERY_CHARS = 256
MAX_OPTIONS = 16
MAX_MODEL_THREAD_DIAMETER_MM = 64.0
MAX_MODEL_THREAD_AXIAL_LENGTH_MM = 250.0
MAX_MODEL_THREAD_TURNS = 512.0
# Zero denotes no fixed object-count ceiling; retained for capability consumers.
MAX_MODEL_THREAD_OBJECTS_PER_DOCUMENT = 0

PROP_SCHEMA = "SteveCADFastenerSchema"
PROP_CATALOG = "SteveCADFastenerCatalog"
PROP_CATALOG_VERSION = "SteveCADFastenerCatalogVersion"
PROP_GENERATOR_REVISION = "SteveCADFastenerGeneratorRevision"
PROP_STANDARD = "SteveCADFastenerStandard"
PROP_FAMILY = "SteveCADFastenerFamily"
PROP_NOMINAL_SIZE = "SteveCADFastenerNominalSize"
PROP_NOMINAL_DIAMETER = "SteveCADFastenerNominalDiameter"
PROP_LENGTH = "SteveCADFastenerLength"
PROP_CANONICAL_KEY = "SteveCADFastenerCanonicalKey"
PROP_CANONICAL_IDENTITY = "SteveCADFastenerCanonicalIdentity"
PROP_INTERFACES = "SteveCADStandardInterfaces"
PROP_CATALOG_PART_NUMBER = "SteveCADCatalogPartNumber"
PROP_ERROR = "SteveCADFastenerError"
PROP_HOLE_SCHEMA = "SteveCADFastenerHoleSchema"
PROP_HOLE_FASTENER_KEY = "SteveCADFastenerHoleComponentKey"
PROP_HOLE_PURPOSE = "SteveCADFastenerHolePurpose"
PROP_HOLE_FIT = "SteveCADFastenerHoleFit"
PROP_HOLE_RESOLUTION = "SteveCADFastenerHoleResolution"

_PROPERTY_GROUP = "SteveCAD Standard Component"
_READ_ONLY_PROPERTIES = frozenset(
    {
        PROP_SCHEMA,
        PROP_CATALOG,
        PROP_CATALOG_VERSION,
        PROP_GENERATOR_REVISION,
        PROP_STANDARD,
        PROP_FAMILY,
        PROP_NOMINAL_SIZE,
        PROP_NOMINAL_DIAMETER,
        PROP_LENGTH,
        PROP_CANONICAL_KEY,
        PROP_CANONICAL_IDENTITY,
        PROP_INTERFACES,
        PROP_CATALOG_PART_NUMBER,
        PROP_ERROR,
        PROP_HOLE_SCHEMA,
        PROP_HOLE_FASTENER_KEY,
        PROP_HOLE_PURPOSE,
        PROP_HOLE_FIT,
        PROP_HOLE_RESOLUTION,
    }
)
_PROVENANCE_FIELDS = frozenset(
    {
        "name",
        "module",
        "version",
        "revision",
        "source",
        "license",
        "license_file",
    }
)
_OPTION_PROPERTIES: dict[str, tuple[str, str, str]] = {
    "body_width_code": ("widthCode", "Width", "enumeration"),
    "pitch": ("Pitch", "Pitch", "enumeration"),
    "thickness_code": ("ThicknessCode", "Tcode", "enumeration"),
    "slot_width": ("SlotWidth", "SlotWidth", "enumeration"),
    "key_size": ("KeySize", "KeySize", "enumeration"),
    "blind": ("blindness", "Blind", "boolean"),
    "external_diameter_mm": ("ExternalDiam", "ExternalDiam", "length"),
    "thread_length_mm": ("ThreadLength", "ScrewLength", "length"),
    "number_of_starts": ("NumStarts", "NumStarts", "integer"),
}
_UPSTREAM: dict[str, Any] | None = None
_PROVENANCE: dict[str, str] | None = None
_NOMINAL_SIZE_PARTITIONS: dict[
    str,
    tuple[tuple[str, ...], tuple[tuple[str, str], ...]],
] = {}
_STANDARD_PARTITION: tuple[tuple[str, ...], tuple[tuple[str, str], ...]] | None = None
_CATALOG_SEARCH_TOKEN_RE = re.compile(
    r"[a-z0-9#]+(?:[./][a-z0-9#]+)*"
)

# This list is generated by the release matrix for the exact pinned revision.
# Rows stay out of every SteveCAD selector until a reviewed upstream revision
# generates one valid solid for them. The complete upstream workbench and its
# source remain bundled; this list only defines the validated shared catalog.
_PINNED_GENERATOR_ROW_EXCLUSIONS = frozenset(
    {
        ("ASMEB18.6.1.3", "#7"),
        ("ASMEB18.6.1.3", "#9"),
        ("ASMEB18.6.1.5", "#7"),
        ("ASMEB18.6.1.5", "#9"),
        ("DIN6331", "M8"),
        ("DIN7979", "10 mm"),
        ("DIN935", "(M7)"),
        ("ISO14579", "(M18)"),
        ("ISO14580", "M1.6"),
        ("ISO4026", "M1.4"),
        ("ISO4027", "M1.4"),
        ("ISO4028", "M1.6"),
        ("ISO4028", "M2"),
        ("ISO4029", "M1.4"),
        *{("ISO8733", size) for size in (
            "6 mm",
            "8 mm",
            "10 mm",
            "12 mm",
            "16 mm",
            "20 mm",
            "25 mm",
            "30 mm",
            "40 mm",
            "50 mm",
        )},
        *{("ISO8735", size) for size in (
            "6 mm",
            "8 mm",
            "10 mm",
            "12 mm",
            "16 mm",
            "20 mm",
            "25 mm",
            "30 mm",
            "40 mm",
            "50 mm",
        )},
    }
)


class FastenerCatalogError(ValueError):
    """A direct catalog or standard-component validation failure."""


def _bounded_text(value: Any, *, name: str, maximum: int = 4096) -> str:
    text = str(value or "").strip()
    if not text:
        raise FastenerCatalogError(f"{name} must be non-empty.")
    if len(text) > maximum:
        raise FastenerCatalogError(
            f"{name} must contain at most {maximum} characters."
        )
    return text


def _catalog_search_terms(value: Any) -> tuple[str, ...]:
    return tuple(
        _CATALOG_SEARCH_TOKEN_RE.findall(str(value or "").casefold())
    )


def _catalog_search_rank(
    query: Any,
    row: Mapping[str, Any],
) -> tuple[int, ...] | None:
    """Rank generic partial matches without interpreting catalog semantics."""

    query_terms = _catalog_search_terms(query)
    if not query_terms:
        return ()
    fields = [
        str(row.get("standard") or "").casefold(),
        str(row.get("family") or "").casefold(),
        str(row.get("description") or "").casefold(),
        *[
            str(value).casefold()
            for value in row.get("nominal_threads", [])
        ],
    ]
    field_words = [
        _catalog_search_terms(field)
        for field in fields
    ]
    scores = []
    for term in query_terms:
        candidates = []
        for field, words in zip(fields, field_words):
            if term == field:
                candidates.append(0)
            elif term in words:
                candidates.append(1)
            elif field.startswith(term):
                candidates.append(2)
            elif any(word.startswith(term) for word in words):
                candidates.append(3)
            elif term in field:
                candidates.append(4)
        if not candidates:
            return None
        scores.append(min(candidates))
    return (sum(scores), *scores)


def _module_root() -> Path:
    return Path(__file__).resolve().parent


def _fasteners_root() -> Path:
    sibling = _module_root().parent / "Fasteners"
    if (sibling / "ScrewMaker.py").is_file():
        return sibling
    try:
        import FreeCAD as App

        installed = Path(str(App.getHomePath())) / "Mod" / "Fasteners"
        if (installed / "ScrewMaker.py").is_file():
            return installed
    except Exception:
        pass
    return sibling


def _load_provenance() -> dict[str, str]:
    global _PROVENANCE
    if _PROVENANCE is not None:
        return dict(_PROVENANCE)
    path = _module_root() / PROVENANCE_FILE
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise FastenerCatalogError(
            f"Bundled Fasteners provenance is unavailable at {path}: {exc}"
        ) from exc
    if not isinstance(value, Mapping) or set(value) != _PROVENANCE_FIELDS:
        raise FastenerCatalogError(
            "Bundled Fasteners provenance has an unsupported schema."
        )
    clean = {name: _bounded_text(value[name], name=name) for name in value}
    if not re.fullmatch(r"[0-9a-f]{40}", clean["revision"]):
        raise FastenerCatalogError(
            "Bundled Fasteners provenance has an invalid revision."
        )
    if clean["module"] != "Fasteners" or clean["license"] != "GPL-2.0-or-later":
        raise FastenerCatalogError(
            "Bundled Fasteners provenance changed its module or license identity."
        )
    _PROVENANCE = clean
    return dict(clean)


def provenance() -> dict[str, str]:
    """Return the exact source, revision, version, and license in this build."""

    return _load_provenance()


def model_thread_limits() -> dict[str, float | int]:
    """Return geometry limits; a zero document count means unlimited objects."""

    return {
        "maximum_nominal_diameter_mm": MAX_MODEL_THREAD_DIAMETER_MM,
        "maximum_axial_length_mm": MAX_MODEL_THREAD_AXIAL_LENGTH_MM,
        "maximum_turns": MAX_MODEL_THREAD_TURNS,
        "maximum_objects_per_document": (
            MAX_MODEL_THREAD_OBJECTS_PER_DOCUMENT
        ),
    }


def _load_upstream() -> dict[str, Any]:
    global _UPSTREAM
    if _UPSTREAM is not None:
        return _UPSTREAM
    module_root = _fasteners_root()
    if not (module_root / "ScrewMaker.py").is_file():
        raise FastenerCatalogError(
            f"The bundled Fasteners module is missing at {module_root}."
        )
    module_path = str(module_root)
    if module_path not in sys.path:
        sys.path.insert(0, module_path)
    try:
        screw_maker = importlib.import_module("ScrewMaker")
        fasteners_cmd = importlib.import_module("FastenersCmd")
        fastener_base = importlib.import_module("FastenerBase")
        fs_aliases = importlib.import_module("FSAliases")
        fs_utils = importlib.import_module("FSutils")
        fs_functions = importlib.import_module("FsFunctions")
    except Exception as exc:
        raise FastenerCatalogError(
            f"The bundled Fasteners module could not load: {exc}"
        ) from exc
    expected_root = module_root.resolve()
    loaded_modules = {
        "ScrewMaker": screw_maker,
        "FastenersCmd": fasteners_cmd,
        "FastenerBase": fastener_base,
        "FSAliases": fs_aliases,
        "FSutils": fs_utils,
    }
    origin_modules = {
        **loaded_modules,
        "screw_maker": sys.modules.get("screw_maker"),
        "FsFunctions": fs_functions,
        **{
            name: module
            for name, module in sys.modules.items()
            if name.startswith("FsFunctions.")
        },
    }
    for module_name, module in origin_modules.items():
        origin = Path(str(getattr(module, "__file__", "") or "")).resolve()
        if not origin.is_relative_to(expected_root):
            raise FastenerCatalogError(
                f"{module_name} loaded from {origin}, but this release requires "
                f"the pinned bundled module at {expected_root}. Remove or "
                "disable the shadowing user-installed Fasteners workbench."
            )
    if not isinstance(getattr(screw_maker, "screwTables", None), Mapping):
        raise FastenerCatalogError(
            "The bundled Fasteners module has no supported catalog table."
        )
    _UPSTREAM = loaded_modules
    return _UPSTREAM


def require_available() -> dict[str, Any]:
    """Load the pinned headless catalog or raise one actionable failure."""

    modules = _load_upstream()
    supported, excluded = _standard_partition()
    return {
        "schema": CATALOG_SCHEMA,
        "catalog": CATALOG_ID,
        "provenance": provenance(),
        "standards": len(supported),
        "upstream_standards": len(modules["ScrewMaker"].screwTables),
        "excluded_upstream_standards": excluded,
        "model_thread_limits": model_thread_limits(),
    }


def _standard_lookup() -> dict[str, str]:
    standards, _excluded = _standard_partition()
    result: dict[str, str] = {}
    for standard in standards:
        key = re.sub(r"\s+", "", standard).casefold()
        if key in result and result[key] != standard:
            raise FastenerCatalogError(
                f"Fasteners standards {result[key]!r} and {standard!r} normalize "
                "to the same identity."
            )
        result[key] = standard
    return result


def canonical_standard(value: Any) -> str:
    requested = _bounded_text(value, name="standard", maximum=128)
    key = re.sub(r"\s+", "", requested).casefold()
    lookup = _standard_lookup()
    if key not in lookup:
        _supported, excluded = _standard_partition()
        excluded_lookup = {
            re.sub(r"\s+", "", item["standard"]).casefold(): item
            for item in excluded
        }
        if key in excluded_lookup:
            raise FastenerCatalogError(
                f"standard {requested!r} is present upstream but excluded from "
                "the validated SteveCAD catalog: "
                f"{excluded_lookup[key]['reason']}."
            )
        matches = sorted(
            standard
            for standard in lookup.values()
            if key and key in standard.casefold()
        )[:20]
        suggestion = f" Matching standards: {matches}." if matches else ""
        raise FastenerCatalogError(
            f"standard {requested!r} is not in the bundled Fasteners catalog."
            f"{suggestion}"
        )
    return lookup[key]


def _catalog_token(
    requested: Any,
    allowed: Sequence[Any],
    *,
    name: str,
    maximum_returned: int = 128,
) -> str:
    text = _bounded_text(requested, name=name, maximum=128)
    normalized = re.sub(r"\s+", "", text).casefold()
    matches = [
        str(item)
        for item in allowed
        if re.sub(r"\s+", "", str(item)).casefold() == normalized
    ]
    if len(matches) == 1:
        return matches[0]
    clean_allowed = [str(item) for item in allowed]
    suffix = " (truncated)" if len(clean_allowed) > maximum_returned else ""
    raise FastenerCatalogError(
        f"{name} {text!r} is unavailable. Valid values: "
        f"{clean_allowed[:maximum_returned]}{suffix}."
    )


def _finite_number(
    value: Any,
    *,
    name: str,
    positive: bool = False,
) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise FastenerCatalogError(f"{name} must be a finite number.")
    result = float(value)
    if not math.isfinite(result):
        raise FastenerCatalogError(f"{name} must be finite.")
    if positive and result <= 0.0:
        raise FastenerCatalogError(f"{name} must be greater than zero.")
    return result


def _model_thread(value: Any) -> bool:
    if not isinstance(value, bool):
        raise FastenerCatalogError("model_thread must be a boolean.")
    return value


def _standard_parameters(standard: str) -> set[str]:
    params = _load_upstream()["FastenersCmd"].FSGetParams(standard)
    return {str(item) for item in params}


def _raw_nominal_sizes(standard: str) -> list[str]:
    maker = _load_upstream()["ScrewMaker"].Instance
    try:
        return [str(item) for item in maker.GetAllDiams(standard)]
    except Exception as exc:
        raise FastenerCatalogError(
            f"Could not read catalog sizes for {standard}: {exc}"
        ) from exc


def _nominal_size_partition(
    standard: str,
) -> tuple[list[str], list[dict[str, str]]]:
    """Separate generator-usable sizes from incomplete upstream table rows."""

    cached = _NOMINAL_SIZE_PARTITIONS.get(standard)
    if cached is not None:
        usable, excluded = cached
        return list(usable), [
            {"nominal_thread": nominal_thread, "reason": reason}
            for nominal_thread, reason in excluded
        ]
    maker = _load_upstream()["ScrewMaker"].Instance
    parameters = _standard_parameters(standard)
    usable = []
    excluded = []
    for nominal_size in _raw_nominal_sizes(standard):
        if (standard, nominal_size) in _PINNED_GENERATOR_ROW_EXCLUSIONS:
            excluded.append(
                {
                    "nominal_thread": nominal_size,
                    "reason": (
                        "The pinned generator failed the release matrix for "
                        "this published row because it did not produce one "
                        "valid solid."
                    ),
                }
            )
            continue
        try:
            width = None
            for name, (requirement, _property, kind) in _OPTION_PROPERTIES.items():
                if requirement not in parameters or kind != "enumeration":
                    continue
                values = _catalog_option_values(
                    standard,
                    nominal_size,
                    name,
                )
                if name == "body_width_code":
                    width = values[0]
            if (
                {"Length", "LenByDiamAndWidth"}.intersection(parameters)
                and "lengthArbitrary" not in parameters
            ):
                lengths = list(
                    maker.GetAllLengths(
                        standard,
                        nominal_size,
                        False,
                        width,
                    )
                )
                if not lengths:
                    raise FastenerCatalogError(
                        "the upstream length table is empty"
                    )
            _nominal_diameter_mm(standard, nominal_size)
        except Exception as exc:
            excluded.append(
                {
                    "nominal_thread": nominal_size,
                    "reason": f"{type(exc).__name__}: {exc}",
                }
            )
        else:
            usable.append(nominal_size)
    if not usable:
        raise FastenerCatalogError(
            f"{standard} has no complete nominal-size rows in the pinned "
            "generator catalog."
        )
    _NOMINAL_SIZE_PARTITIONS[standard] = (
        tuple(usable),
        tuple(
            (item["nominal_thread"], item["reason"])
            for item in excluded
        ),
    )
    return list(usable), [dict(item) for item in excluded]


def _nominal_sizes(standard: str) -> list[str]:
    return _nominal_size_partition(standard)[0]


def _standard_partition() -> tuple[list[str], list[dict[str, str]]]:
    """Return standards with at least one release-validated nominal row."""

    global _STANDARD_PARTITION
    if _STANDARD_PARTITION is not None:
        supported, excluded = _STANDARD_PARTITION
        return list(supported), [
            {"standard": standard, "reason": reason}
            for standard, reason in excluded
        ]
    supported = []
    excluded = []
    for standard in sorted(
        str(item) for item in _load_upstream()["ScrewMaker"].screwTables
    ):
        try:
            _nominal_size_partition(standard)
        except FastenerCatalogError as exc:
            excluded.append(
                {
                    "standard": standard,
                    "reason": str(exc),
                }
            )
        else:
            supported.append(standard)
    _STANDARD_PARTITION = (
        tuple(supported),
        tuple((item["standard"], item["reason"]) for item in excluded),
    )
    return list(supported), [dict(item) for item in excluded]


def _catalog_option_values(
    standard: str,
    nominal_size: str,
    name: str,
) -> list[str]:
    maker = _load_upstream()["ScrewMaker"].Instance
    if name == "body_width_code":
        allowed = maker.GetAllWidthcodes(standard, nominal_size)
    elif name == "pitch":
        allowed = maker.GetAllPitches(standard, nominal_size, False)
    elif name == "thickness_code":
        allowed = maker.GetAllTcodes(standard, nominal_size)
    elif name == "slot_width":
        allowed = maker.GetAllSlotWidths(standard, nominal_size)
    elif name == "key_size":
        allowed = maker.GetAllKeySizes(standard, nominal_size)
    else:
        raise FastenerCatalogError(
            f"option {name!r} is not a catalog enumeration."
        )
    values = [str(item) for item in allowed]
    if not values:
        raise FastenerCatalogError(
            f"{standard} {nominal_size} has no catalog values for "
            f"option {name!r}."
        )
    return values


def _option_values(
    standard: str,
    nominal_size: str,
    options: Mapping[str, Any],
) -> dict[str, Any]:
    if len(options) > MAX_OPTIONS:
        raise FastenerCatalogError(
            f"options may contain at most {MAX_OPTIONS} entries."
        )
    parameters = _standard_parameters(standard)
    maker = _load_upstream()["ScrewMaker"].Instance
    clean: dict[str, Any] = {}
    unknown = sorted(set(str(item) for item in options) - set(_OPTION_PROPERTIES))
    if unknown:
        raise FastenerCatalogError(
            f"options contains unknown keys {unknown}. Supported keys: "
            f"{sorted(_OPTION_PROPERTIES)}."
        )
    for name, (requirement, _property, kind) in _OPTION_PROPERTIES.items():
        if requirement not in parameters:
            continue
        if kind == "boolean":
            clean[name] = False
        elif kind == "integer":
            clean[name] = 1
        elif kind == "length":
            if name == "external_diameter_mm":
                clean[name] = float(
                    maker.GetTableProperty(
                        standard,
                        nominal_size,
                        "ExtDia",
                        8.0,
                    )
                )
            elif name == "thread_length_mm":
                clean[name] = float(
                    maker.GetThreadLength(standard, nominal_size)
                )
            else:
                raise AssertionError(f"Unhandled fastener option {name!r}.")
        else:
            values = _catalog_option_values(standard, nominal_size, name)
            clean[name] = values[0]

    for raw_name, raw_value in options.items():
        name = str(raw_name)
        requirement, _property, kind = _OPTION_PROPERTIES[name]
        if requirement not in parameters:
            raise FastenerCatalogError(
                f"option {name!r} does not apply to {standard}."
            )
        if kind == "boolean":
            if not isinstance(raw_value, bool):
                raise FastenerCatalogError(f"options.{name} must be a boolean.")
            clean[name] = raw_value
        elif kind == "length":
            clean[name] = _finite_number(
                raw_value,
                name=f"options.{name}",
                positive=True,
            )
        elif kind == "integer":
            if (
                isinstance(raw_value, bool)
                or not isinstance(raw_value, int)
                or not 1 <= raw_value <= 4
            ):
                raise FastenerCatalogError(
                    f"options.{name} must be an integer from 1 through 4."
                )
            clean[name] = int(raw_value)
        else:
            clean[name] = _catalog_token(
                raw_value,
                _catalog_option_values(standard, nominal_size, name),
                name=f"options.{name}",
            )
    return clean


def _available_options(
    standard: str,
    nominal_size: str,
    defaults: Mapping[str, Any],
) -> dict[str, dict[str, Any]]:
    return {
        name: {
            "default": value,
            **(
                {
                    "allowed": _catalog_option_values(
                        standard,
                        nominal_size,
                        name,
                    )
                }
                if _OPTION_PROPERTIES[name][2] == "enumeration"
                else {}
            ),
        }
        for name, value in defaults.items()
    }


def _nominal_diameter_mm(standard: str, nominal_size: str) -> float:
    """Resolve a positive characteristic diameter, including range designations."""

    modules = _load_upstream()
    try:
        value = float(modules["FastenerBase"].DiaStr2Num(nominal_size))
    except (TypeError, ValueError):
        match = re.fullmatch(
            r"\s*([0-9]+(?:\.[0-9]+)?)\s*-\s*"
            r"([0-9]+(?:\.[0-9]+)?)\s*(mm|in)?\s*",
            nominal_size,
            flags=re.IGNORECASE,
        )
        if match is None:
            raise FastenerCatalogError(
                f"The catalog cannot resolve a nominal diameter for "
                f"{standard} {nominal_size}."
            )
        low = float(match.group(1))
        high = float(match.group(2))
        value = (low + high) * 0.5
        if str(match.group(3) or "mm").lower() == "in":
            value *= 25.4
    if not math.isfinite(value) or value <= 0.0:
        raise FastenerCatalogError(
            f"The catalog cannot resolve a positive nominal diameter for "
            f"{standard} {nominal_size}."
        )
    return value


def _length_resolution(
    standard: str,
    nominal_size: str,
    length_mm: Any,
    options: Mapping[str, Any],
) -> tuple[str | None, float | None, list[str]]:
    modules = _load_upstream()
    maker = modules["ScrewMaker"].Instance
    parameters = _standard_parameters(standard)
    has_length = bool(
        {"Length", "LenByDiamAndWidth", "lengthArbitrary"}.intersection(parameters)
    )
    if not has_length:
        if length_mm is not None:
            raise FastenerCatalogError(
                f"length_mm does not apply to {standard}."
            )
        return None, None, []
    if length_mm is None:
        raise FastenerCatalogError(f"length_mm is required for {standard}.")
    requested = _finite_number(length_mm, name="length_mm", positive=True)
    if "lengthArbitrary" in parameters:
        return None, requested, []
    width = (
        str(options.get("body_width_code"))
        if "LenByDiamAndWidth" in parameters
        else None
    )
    try:
        allowed = [
            str(item)
            for item in maker.GetAllLengths(
                standard,
                nominal_size,
                False,
                width,
            )
        ]
    except Exception as exc:
        raise FastenerCatalogError(
            f"Could not read lengths for {standard} {nominal_size}: {exc}"
        ) from exc
    matches = []
    for token in allowed:
        try:
            millimeters = float(modules["FastenerBase"].LenStr2Num(token))
        except Exception:
            continue
        if math.isclose(millimeters, requested, rel_tol=0.0, abs_tol=1.0e-7):
            matches.append((token, millimeters))
    if len(matches) != 1:
        allowed_mm = [
            float(modules["FastenerBase"].LenStr2Num(token))
            for token in allowed
        ]
        raise FastenerCatalogError(
            f"length_mm {requested:g} is unavailable for {standard} "
            f"{nominal_size}. Valid catalog lengths in millimeters: {allowed_mm}."
        )
    return matches[0][0], matches[0][1], allowed


def resolve_fastener(
    *,
    standard: Any,
    nominal_thread: Any,
    length_mm: Any = None,
    model_thread: bool = False,
    left_handed: bool = False,
    options: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Resolve one exact standard/size/length request without substitution."""

    if not isinstance(left_handed, bool):
        raise FastenerCatalogError("left_handed must be a boolean.")
    clean_model_thread = _model_thread(model_thread)
    clean_standard = canonical_standard(standard)
    nominal_size = _catalog_token(
        nominal_thread,
        _nominal_sizes(clean_standard),
        name="nominal_thread",
    )
    if options is None:
        raw_options: Mapping[str, Any] = {}
    elif isinstance(options, Mapping):
        raw_options = options
    else:
        raise FastenerCatalogError("options must be an object.")
    clean_options = _option_values(
        clean_standard,
        nominal_size,
        raw_options,
    )
    length_token, clean_length, allowed_lengths = _length_resolution(
        clean_standard,
        nominal_size,
        length_mm,
        clean_options,
    )
    parameters = _standard_parameters(clean_standard)
    if left_handed and "LeftHanded" not in parameters:
        raise FastenerCatalogError(
            f"left_handed does not apply to {clean_standard}."
        )
    if clean_model_thread and "Thread" not in parameters:
        raise FastenerCatalogError(
            f"model_thread does not apply to {clean_standard}."
        )
    modules = _load_upstream()
    family = str(
        modules["ScrewMaker"].Instance.GetTypeName(clean_standard)
    )
    description = str(
        modules["FastenersCmd"].FSGetDescription(clean_standard) or family
    ).strip()
    nominal_diameter = _nominal_diameter_mm(clean_standard, nominal_size)
    identity = {
        "schema": COMPONENT_SCHEMA,
        "catalog": CATALOG_ID,
        "catalog_version": provenance()["version"],
        "generator_revision": provenance()["revision"],
        "standard": clean_standard,
        "family": family,
        "nominal_size": nominal_size,
        "nominal_diameter_mm": nominal_diameter,
        "length_token": length_token,
        "length_mm": clean_length,
        "model_thread": clean_model_thread,
        "left_handed": left_handed,
        "options": clean_options,
    }
    _validate_model_thread_limits(identity)
    encoded = json.dumps(
        identity,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    )
    digest = hashlib.sha256(encoded.encode("utf-8")).hexdigest()
    dimensions = nominal_size
    if clean_length is not None:
        dimensions += f"x{clean_length:g}"
    part_number = f"{clean_standard} {dimensions}"
    if left_handed:
        part_number += " LH"
    if clean_options:
        part_number += " [" + ",".join(
            f"{name}={clean_options[name]}" for name in sorted(clean_options)
        ) + "]"
    identity.update(
        {
            "canonical_key": f"{CATALOG_ID}:{digest}",
            "part_number": part_number,
            "description": description,
            "allowed_length_tokens": allowed_lengths,
        }
    )
    return identity


def describe_standard(
    standard: Any,
    *,
    nominal_thread: Any | None = None,
) -> dict[str, Any]:
    """Describe one standard and, optionally, its size-dependent lengths."""

    clean_standard = canonical_standard(standard)
    modules = _load_upstream()
    maker = modules["ScrewMaker"].Instance
    parameters = _standard_parameters(clean_standard)
    sizes, excluded_sizes = _nominal_size_partition(clean_standard)
    result: dict[str, Any] = {
        "schema": CATALOG_SCHEMA,
        "catalog": CATALOG_ID,
        "catalog_version": provenance()["version"],
        "generator_revision": provenance()["revision"],
        "standard": clean_standard,
        "family": str(maker.GetTypeName(clean_standard)),
        "description": str(
            modules["FastenersCmd"].FSGetDescription(clean_standard)
            or maker.GetTypeName(clean_standard)
        ).strip(),
        "nominal_threads": sizes,
        "excluded_upstream_nominal_threads": excluded_sizes,
        "requires_length": bool(
            {"Length", "LenByDiamAndWidth", "lengthArbitrary"}.intersection(
                parameters
            )
        ),
        "arbitrary_length": "lengthArbitrary" in parameters,
        "supports_model_thread": "Thread" in parameters,
        "supports_left_handed": "LeftHanded" in parameters,
        "model_thread_limits": model_thread_limits(),
        "option_names": sorted(
            name
            for name, (requirement, _property, _kind) in _OPTION_PROPERTIES.items()
            if requirement in parameters
        ),
    }
    if nominal_thread is not None:
        size = _catalog_token(
            nominal_thread,
            sizes,
            name="nominal_thread",
        )
        result["nominal_thread"] = size
        defaults = _option_values(clean_standard, size, {})
        result["options"] = _available_options(
            clean_standard,
            size,
            defaults,
        )
        if result["requires_length"] and not result["arbitrary_length"]:
            width = (
                str(defaults["body_width_code"])
                if "LenByDiamAndWidth" in parameters
                else None
            )
            tokens = [
                str(item)
                for item in maker.GetAllLengths(
                    clean_standard,
                    size,
                    False,
                    width,
                )
            ]
            result["lengths"] = [
                {
                    "token": token,
                    "millimeters": float(
                        modules["FastenerBase"].LenStr2Num(token)
                    ),
                }
                for token in tokens
            ]
            if "LenByDiamAndWidth" in parameters:
                result["lengths_depend_on_option"] = "body_width_code"
        elif result["requires_length"]:
            result["default_length_mm"] = float(
                maker.GetTableProperty(
                    clean_standard,
                    size,
                    "Length",
                    20.0,
                )
            )
    return result


def catalog_index() -> dict[str, Any]:
    """Return every release-validated standard and upstream exclusions."""

    modules = _load_upstream()
    maker = modules["ScrewMaker"].Instance
    supported, excluded = _standard_partition()
    standards = []
    for standard in supported:
        parameters = _standard_parameters(standard)
        nominal_threads, excluded_threads = _nominal_size_partition(standard)
        standards.append(
            {
                "standard": standard,
                "family": str(maker.GetTypeName(standard)),
                "description": str(
                    modules["FastenersCmd"].FSGetDescription(standard)
                    or maker.GetTypeName(standard)
                ).strip(),
                "requires_length": bool(
                    {
                        "Length",
                        "LenByDiamAndWidth",
                        "lengthArbitrary",
                    }.intersection(parameters)
                ),
                "supports_model_thread": "Thread" in parameters,
                "supports_left_handed": "LeftHanded" in parameters,
                "nominal_threads": nominal_threads,
                "nominal_thread_count": len(nominal_threads),
                "excluded_upstream_nominal_threads": excluded_threads,
            }
        )
    return {
        "schema": CATALOG_SCHEMA,
        "catalog": CATALOG_ID,
        "catalog_version": provenance()["version"],
        "generator_revision": provenance()["revision"],
        "model_thread_limits": model_thread_limits(),
        "upstream_standard_count": len(modules["ScrewMaker"].screwTables),
        "excluded_upstream_standards": excluded,
        "standards": standards,
    }


def search_catalog(
    query: Any = "",
    *,
    family: Any | None = None,
    standard: Any | None = None,
    nominal_thread: Any | None = None,
    length_mm: Any | None = None,
    limit: int = 25,
) -> dict[str, Any]:
    """Search the complete bundled catalog with deterministic exact values."""

    if (
        isinstance(limit, bool)
        or not isinstance(limit, int)
        or not 1 <= limit <= MAX_SEARCH_RESULTS
    ):
        raise FastenerCatalogError(
            f"limit must be an integer from 1 through {MAX_SEARCH_RESULTS}."
        )
    query_text = str(query or "").strip()
    if len(query_text) > MAX_SEARCH_QUERY_CHARS:
        raise FastenerCatalogError(
            f"query must contain at most {MAX_SEARCH_QUERY_CHARS} characters."
        )
    family_text = str(family or "").strip().casefold()
    exact_standard = canonical_standard(standard) if standard is not None else None
    thread_text = (
        re.sub(r"\s+", "", str(nominal_thread)).casefold()
        if nominal_thread is not None
        else ""
    )
    requested_length = (
        None
        if length_mm is None
        else _finite_number(length_mm, name="length_mm", positive=True)
    )
    if requested_length is not None and not thread_text:
        raise FastenerCatalogError(
            "nominal_thread is required when length_mm is provided."
        )
    modules = _load_upstream()
    maker = modules["ScrewMaker"].Instance
    ranked_rows: list[
        tuple[tuple[int, ...], str, dict[str, Any]]
    ] = []
    supported_standards, excluded_standards = _standard_partition()
    for candidate in supported_standards:
        if exact_standard is not None and candidate != exact_standard:
            continue
        candidate_family = str(maker.GetTypeName(candidate))
        if family_text and candidate_family.casefold() != family_text:
            continue
        sizes = _nominal_sizes(candidate)
        if thread_text and not any(
            re.sub(r"\s+", "", item).casefold() == thread_text for item in sizes
        ):
            continue
        description = str(
            modules["FastenersCmd"].FSGetDescription(candidate)
            or candidate_family
        ).strip()
        search_rank = _catalog_search_rank(
            query_text,
            {
                "standard": candidate,
                "family": candidate_family,
                "description": description,
                "nominal_threads": sizes,
            },
        )
        if search_rank is None:
            continue
        parameters = _standard_parameters(candidate)
        row: dict[str, Any] = {
            "standard": candidate,
            "family": candidate_family,
            "description": description,
            "nominal_threads": sizes,
            "requires_length": bool(
                {
                    "Length",
                    "LenByDiamAndWidth",
                    "lengthArbitrary",
                }.intersection(parameters)
            ),
            "supports_model_thread": "Thread" in parameters,
            "supports_left_handed": "LeftHanded" in parameters,
            "option_names": sorted(
                name
                for name, (
                    requirement,
                    _property,
                    _kind,
                ) in _OPTION_PROPERTIES.items()
                if requirement in parameters
            ),
        }
        if thread_text:
            selected_size = next(
                item
                for item in sizes
                if re.sub(r"\s+", "", item).casefold() == thread_text
            )
            defaults = _option_values(candidate, selected_size, {})
            row["nominal_thread"] = selected_size
            row["default_options"] = defaults
            row["available_options"] = _available_options(
                candidate,
                selected_size,
                defaults,
            )
            if row["requires_length"] and "lengthArbitrary" not in parameters:
                width = (
                    str(defaults["body_width_code"])
                    if "LenByDiamAndWidth" in parameters
                    else None
                )
                tokens = [
                    str(item)
                    for item in maker.GetAllLengths(
                        candidate,
                        selected_size,
                        False,
                        width,
                    )
                ]
                valid_lengths = [
                    float(modules["FastenerBase"].LenStr2Num(token))
                    for token in tokens
                ]
                row["valid_lengths_mm"] = valid_lengths
            elif row["requires_length"]:
                valid_lengths = []
                row["arbitrary_positive_length"] = True
            else:
                valid_lengths = []
            request_length = (
                requested_length
                if row["requires_length"]
                else None
            )
            exact = requested_length is None
            if requested_length is not None:
                if not row["requires_length"]:
                    exact = False
                    row["request_error"] = (
                        f"length_mm does not apply to {candidate}."
                    )
                elif "lengthArbitrary" in parameters:
                    exact = True
                else:
                    exact = any(
                        math.isclose(
                            requested_length,
                            value,
                            rel_tol=0.0,
                            abs_tol=1.0e-7,
                        )
                        for value in valid_lengths
                    )
                    if not exact:
                        row["nearest_valid_lengths_mm"] = sorted(
                            valid_lengths,
                            key=lambda value: (
                                abs(value - requested_length),
                                value,
                            ),
                        )[:8]
                        row["request_error"] = (
                            f"length_mm {requested_length:g} is unavailable for "
                            f"{candidate} {selected_size}."
                        )
            row["requested_match"] = exact
            if exact and (
                not row["requires_length"] or requested_length is not None
            ):
                identity = resolve_fastener(
                    standard=candidate,
                    nominal_thread=selected_size,
                    length_mm=request_length,
                    options=defaults,
                )
                row["constructor"] = {
                    "standard": identity["standard"],
                    "nominal_thread": identity["nominal_size"],
                    "length_mm": identity["length_mm"],
                    "model_thread": identity["model_thread"],
                    "left_handed": identity["left_handed"],
                    "options": identity["options"],
                }
                row["canonical_key"] = identity["canonical_key"]
        ranked_rows.append((search_rank, candidate, row))
    ranked_rows.sort(key=lambda item: (item[0], item[1]))
    rows = [item[2] for item in ranked_rows]
    returned = rows[:limit]
    return {
        "schema": CATALOG_SCHEMA,
        "catalog": CATALOG_ID,
        "catalog_version": provenance()["version"],
        "generator_revision": provenance()["revision"],
        "model_thread_limits": model_thread_limits(),
        "excluded_upstream_standards": excluded_standards,
        "query": query_text,
        "requested": {
            "family": str(family or ""),
            "standard": str(standard or ""),
            "nominal_thread": str(nominal_thread or ""),
            "length_mm": requested_length,
        },
        "exact_match_count": sum(
            1
            for row in rows
            if row.get("requested_match") is not False
        ),
        "total_matches": len(rows),
        "returned": len(returned),
        "truncated": len(rows) > len(returned),
        "results": returned,
    }


def _canonical_fastener_identity(value: Any) -> dict[str, Any]:
    if isinstance(value, Mapping):
        supplied = dict(value)
    else:
        encoded = str(
            getattr(value, PROP_CANONICAL_IDENTITY, "") or ""
        ).strip()
        try:
            supplied = json.loads(encoded)
        except (TypeError, ValueError) as exc:
            raise FastenerCatalogError(
                "fastener must be a canonical catalog definition or a SteveCAD "
                "standard-fastener object."
            ) from exc
    if supplied.get("schema") != COMPONENT_SCHEMA:
        raise FastenerCatalogError(
            f"fastener must use schema {COMPONENT_SCHEMA!r}."
        )
    if "model_thread" not in supplied:
        raise FastenerCatalogError(
            "fastener canonical identity is missing model_thread."
        )
    resolved = resolve_fastener(
        standard=supplied.get("standard"),
        nominal_thread=supplied.get("nominal_size"),
        length_mm=supplied.get("length_mm"),
        model_thread=supplied["model_thread"],
        left_handed=supplied.get("left_handed", False),
        options=supplied.get("options"),
    )
    supplied_key = str(supplied.get("canonical_key") or "")
    if supplied_key and supplied_key != resolved["canonical_key"]:
        raise FastenerCatalogError(
            "fastener canonical_key does not match its catalog parameters."
        )
    return resolved


def _native_hole_catalog() -> list[dict[str, Any]]:
    try:
        import PartDesign

        raw = PartDesign.getHoleThreadCatalog()
    except Exception as exc:
        raise FastenerCatalogError(
            f"The native Part Design hole catalog is unavailable: {exc}"
        ) from exc
    if not isinstance(raw, list):
        raise FastenerCatalogError(
            "The native Part Design hole catalog returned an invalid value."
        )
    result = [dict(item) for item in raw if isinstance(item, Mapping)]
    if not result:
        raise FastenerCatalogError(
            "The native Part Design hole catalog is empty."
        )
    return result


def _fastener_pitch_mm(identity: Mapping[str, Any]) -> float:
    options = dict(identity.get("options") or {})
    raw_pitch = options.get("pitch")
    if raw_pitch is not None:
        try:
            pitch = float(
                _load_upstream()["FastenerBase"].LenStr2Num(str(raw_pitch))
            )
        except Exception as exc:
            raise FastenerCatalogError(
                f"Could not resolve pitch option {raw_pitch!r} for "
                f"{identity['standard']} {identity['nominal_size']}."
            ) from exc
    else:
        maker = _load_upstream()["ScrewMaker"].Instance
        try:
            pitch = float(
                maker.GetTableProperty(
                    str(identity["standard"]),
                    str(identity["nominal_size"]),
                    "P",
                    -1.0,
                )
            )
        except Exception as exc:
            raise FastenerCatalogError(
                f"Could not read the thread pitch for {identity['standard']} "
                f"{identity['nominal_size']}: {exc}"
            ) from exc
        if not math.isfinite(pitch) or pitch <= 0.0:
            try:
                threads_per_inch = float(
                    maker.GetTableProperty(
                        str(identity["standard"]),
                        str(identity["nominal_size"]),
                        "TPI",
                        -1.0,
                    )
                )
            except Exception as exc:
                raise FastenerCatalogError(
                    f"Could not read threads per inch for "
                    f"{identity['standard']} {identity['nominal_size']}: {exc}"
                ) from exc
            if math.isfinite(threads_per_inch) and threads_per_inch > 0.0:
                pitch = 25.4 / threads_per_inch
        if not math.isfinite(pitch) or pitch <= 0.0:
            nominal = re.sub(
                r"[\s()]",
                "",
                str(identity["nominal_size"]),
            )
            metric_match = re.fullmatch(
                r"M(?P<diameter>\d+(?:\.\d+)?)"
                r"(?:[xX](?P<pitch>\d+(?:\.\d+)?))?",
                nominal,
            )
            if metric_match and metric_match.group("pitch"):
                pitch = float(metric_match.group("pitch"))
            elif metric_match:
                coarse_table = _load_upstream()["ScrewMaker"].FsData.get(
                    "ISO262def",
                    {},
                )
                coarse_row = coarse_table.get(
                    f"M{metric_match.group('diameter')}"
                )
                if coarse_row and coarse_row[0] not in (None, ""):
                    pitch = float(coarse_row[0])
    if not math.isfinite(pitch) or pitch <= 0.0:
        raise FastenerCatalogError(
            f"{identity['standard']} {identity['nominal_size']} has no standard "
            "thread pitch for real-thread validation or a derived Part "
            "Design hole."
        )
    return pitch


def _validate_model_thread_limits(identity: Mapping[str, Any]) -> None:
    """Reject real threads whose declared geometry exceeds release bounds."""

    if not bool(identity.get("model_thread")):
        return
    diameter = float(identity["nominal_diameter_mm"])
    if diameter > MAX_MODEL_THREAD_DIAMETER_MM:
        raise FastenerCatalogError(
            f"Real thread nominal diameter {diameter:g} mm exceeds the "
            f"{MAX_MODEL_THREAD_DIAMETER_MM:g} mm release limit; use "
            "model_thread=False."
        )
    options = dict(identity.get("options") or {})
    axial_length = identity.get("length_mm")
    if axial_length is None:
        axial_length = options.get("thread_length_mm")
    if axial_length is not None:
        axial_length = float(axial_length)
        if axial_length > MAX_MODEL_THREAD_AXIAL_LENGTH_MM:
            raise FastenerCatalogError(
                f"Real thread axial length {axial_length:g} mm exceeds the "
                f"{MAX_MODEL_THREAD_AXIAL_LENGTH_MM:g} mm release limit; use "
                "model_thread=False."
            )
        pitch = _fastener_pitch_mm(identity)
        turns = axial_length / pitch
        if turns > MAX_MODEL_THREAD_TURNS:
            raise FastenerCatalogError(
                f"Real thread requires {turns:g} turns, exceeding the "
                f"{MAX_MODEL_THREAD_TURNS:g}-turn release limit; use "
                "model_thread=False."
            )


def _native_hole_thread(
    identity: Mapping[str, Any],
) -> tuple[str, dict[str, Any]]:
    diameter = float(identity["nominal_diameter_mm"])
    pitch = _fastener_pitch_mm(identity)
    matches: list[tuple[str, dict[str, Any]]] = []
    for entry in _native_hole_catalog():
        thread_type = str(entry.get("standard") or "")
        if not thread_type or thread_type == "None":
            continue
        for raw_size in list(entry.get("sizes") or []):
            if not isinstance(raw_size, Mapping):
                continue
            size = dict(raw_size)
            try:
                size_diameter = float(size["diameter_mm"])
                size_pitch = float(size["pitch_mm"])
            except (KeyError, TypeError, ValueError):
                continue
            if math.isclose(
                size_diameter,
                diameter,
                rel_tol=0.0,
                abs_tol=1.0e-7,
            ) and math.isclose(
                size_pitch,
                pitch,
                rel_tol=0.0,
                abs_tol=1.0e-7,
            ):
                matches.append((thread_type, size))
    if len(matches) != 1:
        candidates = [
            f"{thread_type}:{size.get('designation')}"
            for thread_type, size in matches
        ]
        raise FastenerCatalogError(
            f"{identity['standard']} {identity['nominal_size']} with pitch "
            f"{pitch:g} mm does not map to exactly one native Part Design "
            f"thread designation. Matches: {candidates}."
        )
    return matches[0]


def _hole_cut_definitions() -> list[dict[str, Any]]:
    try:
        import FreeCAD as App

        root = (
            Path(str(App.getResourceDir()))
            / "Mod"
            / "PartDesign"
            / "Resources"
            / "Hole"
        )
    except Exception as exc:
        raise FastenerCatalogError(
            f"Could not locate Part Design hole definitions: {exc}"
        ) from exc
    definitions: list[dict[str, Any]] = []
    for path in sorted(root.glob("*.json")):
        try:
            raw = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise FastenerCatalogError(
                f"Could not read native hole definition {path.name}: {exc}"
            ) from exc
        if not isinstance(raw, Mapping):
            raise FastenerCatalogError(
                f"Native hole definition {path.name} is not an object."
            )
        definition = dict(raw)
        if (
            not str(definition.get("name") or "").strip()
            or definition.get("cut_type") not in {
                "counterbore",
                "countersink",
            }
            or definition.get("thread_type") not in {
                "metric",
                "metricfine",
            }
            or not isinstance(definition.get("data"), list)
        ):
            raise FastenerCatalogError(
                f"Native hole definition {path.name} has an unsupported schema."
            )
        definitions.append(definition)
    if not definitions:
        raise FastenerCatalogError(
            f"No native Part Design hole definitions were found at {root}."
        )
    return definitions


def _standard_hole_cut(
    identity: Mapping[str, Any],
    *,
    purpose: str,
    thread_type: str,
    designation: str,
) -> dict[str, Any]:
    thread_class = {
        "ISOMetricProfile": "metric",
        "ISOMetricFineProfile": "metricfine",
    }.get(thread_type)
    if thread_class is None:
        raise FastenerCatalogError(
            f"{purpose} dimensions for {identity['standard']} are not published "
            "in the native Part Design hole-definition catalog."
        )
    requested_standard = re.sub(
        r"[^a-z0-9]+",
        "",
        str(identity["standard"]).casefold(),
    )
    matches = []
    for definition in _hole_cut_definitions():
        definition_standard = re.sub(
            r"[^a-z0-9]+",
            "",
            str(definition["name"]).casefold(),
        )
        if (
            definition["cut_type"] != purpose
            or definition["thread_type"] != thread_class
            or definition_standard != requested_standard
        ):
            continue
        dimension = next(
            (
                dict(item)
                for item in definition["data"]
                if isinstance(item, Mapping)
                and str(item.get("thread") or "") == designation
            ),
            None,
        )
        if dimension is not None:
            matches.append((definition, dimension))
    if len(matches) != 1:
        raise FastenerCatalogError(
            f"The native Part Design catalog has no exact {purpose} definition "
            f"for {identity['standard']} {designation}."
        )
    definition, dimension = matches[0]
    return {
        "native_cut_type": str(definition["name"]),
        "expected_diameter_mm": float(dimension["diameter"]),
        **(
            {"expected_depth_mm": float(dimension["depth"])}
            if purpose == "counterbore"
            else {"expected_angle_degrees": float(definition["angle"])}
        ),
    }


def resolve_fastener_hole(
    fastener: Any,
    *,
    purpose: Any,
    fit: Any = "normal",
) -> dict[str, Any]:
    """Resolve a standard component to one exact native Part Design hole setup."""

    identity = _canonical_fastener_identity(fastener)
    clean_purpose = str(purpose or "").strip().lower()
    if clean_purpose not in {
        "clearance",
        "tapped",
        "counterbore",
        "countersink",
    }:
        raise FastenerCatalogError(
            "purpose must be clearance, tapped, counterbore, or countersink."
        )
    clean_fit = str(fit or "").strip().lower()
    if clean_fit not in {"normal", "close", "loose"}:
        raise FastenerCatalogError("fit must be normal, close, or loose.")
    if clean_purpose == "tapped" and clean_fit != "normal":
        raise FastenerCatalogError(
            "fit applies to clearance holes; tapped holes require fit='normal'."
        )
    thread_type, size = _native_hole_thread(identity)
    resolution: dict[str, Any] = {
        "schema": HOLE_SCHEMA,
        "fastener_canonical_key": str(identity["canonical_key"]),
        "fastener_standard": str(identity["standard"]),
        "fastener_nominal_thread": str(identity["nominal_size"]),
        "purpose": clean_purpose,
        "fit": clean_fit,
        "native_thread_type": thread_type,
        "native_thread_size": str(size["designation"]),
        "nominal_diameter_mm": float(size["diameter_mm"]),
        "pitch_mm": float(size["pitch_mm"]),
        "tap_drill_mm": float(size["tap_drill_mm"]),
        "left_handed": bool(identity["left_handed"]),
    }
    if clean_purpose in {"counterbore", "countersink"}:
        resolution.update(
            _standard_hole_cut(
                identity,
                purpose=clean_purpose,
                thread_type=thread_type,
                designation=str(size["designation"]),
            )
        )
    return resolution


def _set_native_enumeration(obj: Any, property_name: str, value: str) -> None:
    choices = [
        str(item)
        for item in list(obj.getEnumerationsOfProperty(property_name) or [])
    ]
    if value not in choices:
        raise FastenerCatalogError(
            f"Native Part Design {property_name} {value!r} is unavailable. "
            f"Valid values: {choices}."
        )
    setattr(obj, property_name, value)


def configure_fastener_hole_feature(
    feature: Any,
    fastener: Any,
    *,
    purpose: Any,
    fit: Any = "normal",
) -> dict[str, Any]:
    """Apply one resolved standard-component hole to a native Hole feature."""

    try:
        native_hole = bool(feature.isDerivedFrom("PartDesign::Hole"))
    except (AttributeError, RuntimeError):
        native_hole = False
    if not native_hole:
        raise FastenerCatalogError(
            "feature must be a native Part Design Hole operation."
        )
    resolution = resolve_fastener_hole(
        fastener,
        purpose=purpose,
        fit=fit,
    )
    _set_native_enumeration(
        feature,
        "ThreadType",
        str(resolution["native_thread_type"]),
    )
    _set_native_enumeration(
        feature,
        "ThreadSize",
        str(resolution["native_thread_size"]),
    )
    tapped = resolution["purpose"] == "tapped"
    feature.Threaded = tapped
    feature.ThreadDirection = (
        "Left" if bool(resolution["left_handed"]) else "Right"
    )
    feature.ModelThread = False
    feature.CosmeticThread = tapped
    if tapped:
        feature.HoleCutType = "None"
    else:
        fit_index = {"normal": 0, "close": 1, "loose": 2}[
            str(resolution["fit"])
        ]
        feature.ThreadFit = fit_index
        native_fit = str(feature.ThreadFit)
        resolution["native_fit"] = native_fit
        if resolution["purpose"] in {"counterbore", "countersink"}:
            _set_native_enumeration(
                feature,
                "HoleCutType",
                str(resolution["native_cut_type"]),
            )
            feature.HoleCutCustomValues = False
        else:
            feature.HoleCutType = "None"
    resolution["resolved_diameter_mm"] = float(feature.Diameter.Value)
    if resolution["purpose"] in {"counterbore", "countersink"}:
        resolution["resolved_cut_diameter_mm"] = float(
            feature.HoleCutDiameter.Value
        )
        expected_diameter = float(resolution["expected_diameter_mm"])
        if not math.isclose(
            resolution["resolved_cut_diameter_mm"],
            expected_diameter,
            rel_tol=0.0,
            abs_tol=1.0e-7,
        ):
            raise FastenerCatalogError(
                f"Native Part Design resolved {resolution['purpose']} diameter "
                f"{resolution['resolved_cut_diameter_mm']:g} mm, expected "
                f"{expected_diameter:g} mm from its packaged definition."
            )
        if resolution["purpose"] == "counterbore":
            resolution["resolved_cut_depth_mm"] = float(
                feature.HoleCutDepth.Value
            )
        else:
            resolution["resolved_cut_angle_degrees"] = float(
                feature.HoleCutCountersinkAngle.Value
            )
    property_specs = (
        (PROP_HOLE_SCHEMA, "Standard-derived hole schema."),
        (PROP_HOLE_FASTENER_KEY, "Canonical fastener used to derive this hole."),
        (PROP_HOLE_PURPOSE, "Standard-derived hole purpose."),
        (PROP_HOLE_FIT, "Standard-derived clearance fit."),
        (PROP_HOLE_RESOLUTION, "Auditable native hole dimensions and designations."),
    )
    for name, description in property_specs:
        _ensure_property(feature, "App::PropertyString", name, description)
    _set_metadata(feature, PROP_HOLE_SCHEMA, HOLE_SCHEMA)
    _set_metadata(
        feature,
        PROP_HOLE_FASTENER_KEY,
        str(resolution["fastener_canonical_key"]),
    )
    _set_metadata(feature, PROP_HOLE_PURPOSE, str(resolution["purpose"]))
    _set_metadata(feature, PROP_HOLE_FIT, str(resolution["fit"]))
    _set_metadata(
        feature,
        PROP_HOLE_RESOLUTION,
        json.dumps(
            resolution,
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ),
    )
    return resolution


def _ensure_property(
    obj: Any,
    type_id: str,
    name: str,
    description: str,
) -> None:
    if name not in set(getattr(obj, "PropertiesList", []) or []):
        obj.addProperty(type_id, name, _PROPERTY_GROUP, description)


def _set_metadata(obj: Any, name: str, value: Any) -> None:
    if name in _READ_ONLY_PROPERTIES:
        try:
            obj.setEditorMode(name, 0)
        except Exception:
            pass
    setattr(obj, name, value)
    if name in _READ_ONLY_PROPERTIES:
        try:
            obj.setEditorMode(name, 1)
        except Exception:
            pass


def _active_length(obj: Any) -> float | None:
    if not hasattr(obj, "Length"):
        return None
    value = obj.Length
    if isinstance(value, str):
        if value == "Custom" and hasattr(obj, "LengthCustom"):
            return float(obj.LengthCustom.Value)
        return float(_load_upstream()["FastenerBase"].LenStr2Num(value))
    if hasattr(value, "Value"):
        return float(value.Value)
    return float(value)


def _interfaces(
    obj: Any,
    family: str,
    nominal_diameter_mm: float,
    *,
    standard: str = "",
    length_mm: float | None = None,
) -> dict[str, Any]:
    shape = getattr(obj, "Shape", None)
    if shape is None or shape.isNull():
        raise FastenerCatalogError(
            f"Fastener {getattr(obj, 'Name', '')!r} has no generated Shape."
        )
    bounds = shape.BoundBox
    # Most upstream screw generators put the under-head bearing face at Z=0
    # and extend the shank toward -Z.  Shoulder screws are deliberately
    # different: their published nominal length is the shoulder length and
    # makeShoulderScrew places the under-head face at Z=length.  Treating that
    # face as Z=0 makes a native fixed joint put the screw head and shaft on
    # the wrong side of the stack.
    bearing_z = 0.0
    if standard in {"ISO7379", "ASMEB18.3.4"}:
        if length_mm is None:
            length_mm = _active_length(obj)
        shoulder_length = float(length_mm)
        if not math.isfinite(shoulder_length) or shoulder_length <= 0.0:
            raise FastenerCatalogError(
                f"{standard} requires a positive shoulder length to publish its "
                "under-head bearing plane."
            )
        bearing_z = shoulder_length
    interfaces: dict[str, Any] = {
        "axis": {
            "kind": "axis",
            "origin_mm": [0.0, 0.0, 0.0],
            "direction": [0.0, 0.0, 1.0],
        },
        "thread_axis": {
            "kind": "axis",
            "origin_mm": [0.0, 0.0, 0.0],
            "direction": [0.0, 0.0, 1.0],
        },
        "mounting_plane": {
            "kind": "plane",
            "origin_mm": [0.0, 0.0, bearing_z],
            "normal": [0.0, 0.0, 1.0],
        },
        "minimum_z_plane": {
            "kind": "plane",
            "origin_mm": [0.0, 0.0, float(bounds.ZMin)],
            "normal": [0.0, 0.0, -1.0],
        },
        "maximum_z_plane": {
            "kind": "plane",
            "origin_mm": [0.0, 0.0, float(bounds.ZMax)],
            "normal": [0.0, 0.0, 1.0],
        },
        "nominal_envelope": {
            "kind": "cylinder",
            "axis_origin_mm": [0.0, 0.0, 0.0],
            "axis_direction": [0.0, 0.0, 1.0],
            "diameter_mm": float(nominal_diameter_mm),
            "minimum_z_mm": float(bounds.ZMin),
            "maximum_z_mm": float(bounds.ZMax),
        },
    }
    if family in {"Screw", "SetScrew", "Stud", "Pin", "Nail"}:
        interfaces["bearing_plane"] = {
            "kind": "plane",
            "origin_mm": [0.0, 0.0, bearing_z],
            "normal": [0.0, 0.0, -1.0],
        }
        interfaces["under_head_plane"] = dict(interfaces["bearing_plane"])
        interfaces["thread_envelope"] = dict(interfaces["nominal_envelope"])
        interfaces["shank_envelope"] = dict(interfaces["nominal_envelope"])
        interfaces["tip_plane"] = dict(interfaces["minimum_z_plane"])
    if family in {"Nut", "Washer", "RetainingRing"}:
        interfaces["first_bearing_plane"] = dict(
            interfaces["minimum_z_plane"]
        )
        interfaces["second_bearing_plane"] = dict(
            interfaces["maximum_z_plane"]
        )
    return {
        "schema": INTERFACE_SCHEMA,
        "interfaces": interfaces,
    }


def catalog_component_reference(identity: Mapping[str, Any]) -> dict[str, str]:
    """Return the stable non-document source identity used by Assembly."""

    if str(identity.get("schema") or "") != COMPONENT_SCHEMA:
        raise FastenerCatalogError(
            "Assembly fastener identity has an unsupported component schema."
        )
    canonical_key = _bounded_text(
        identity.get("canonical_key"),
        name="canonical_key",
    )
    return {
        "document_uid": CATALOG_ID,
        "object_name": canonical_key,
    }


def _interface_frame(interface: Mapping[str, Any]) -> dict[str, list[float]]:
    kind = str(interface.get("kind") or "")
    if kind == "axis":
        position = list(interface.get("origin_mm") or [])
        direction = list(interface.get("direction") or [])
    elif kind == "plane":
        position = list(interface.get("origin_mm") or [])
        direction = list(interface.get("normal") or [])
    elif kind == "cylinder":
        position = list(interface.get("axis_origin_mm") or [])
        direction = list(interface.get("axis_direction") or [])
    else:
        raise FastenerCatalogError(
            f"Standard-component interface kind {kind!r} has no connector frame."
        )
    if len(position) != 3 or len(direction) != 3:
        raise FastenerCatalogError(
            f"Standard-component {kind} interface has malformed vectors."
        )
    def stable(value: Any, *, name: str) -> float:
        result = round(_finite_number(value, name=name), 12)
        return 0.0 if result == 0.0 else result

    clean_position = [
        stable(value, name="interface origin") for value in position
    ]
    clean_direction = [
        stable(value, name="interface direction") for value in direction
    ]
    magnitude = math.sqrt(sum(value * value for value in clean_direction))
    if magnitude <= 1.0e-12:
        raise FastenerCatalogError(
            f"Standard-component {kind} interface has a zero direction."
        )
    dx, dy, dz = (value / magnitude for value in clean_direction)
    # Shortest quaternion rotating the component-local +Z axis onto the
    # published engineering direction. The antiparallel case is an exact
    # half-turn about +X.
    if dz <= -1.0 + 1.0e-12:
        rotation = [1.0, 0.0, 0.0, 0.0]
    else:
        rotation = [-dy, dx, 0.0, 1.0 + dz]
        quaternion_magnitude = math.sqrt(
            sum(value * value for value in rotation)
        )
        rotation = [
            stable(
                value / quaternion_magnitude,
                name="interface rotation",
            )
            for value in rotation
        ]
    return {
        "position": clean_position,
        "rotation": rotation,
    }


def fastener_bom_properties(
    identity: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Return the stable scalar properties consumed by native Assembly BOM."""

    values = (
        ("PartNumber", str(identity.get("part_number") or "")),
        ("Description", str(identity.get("description") or "")),
        (PROP_STANDARD, str(identity.get("standard") or "")),
        (PROP_FAMILY, str(identity.get("family") or "")),
        (PROP_NOMINAL_SIZE, str(identity.get("nominal_size") or "")),
        (PROP_CATALOG_PART_NUMBER, str(identity.get("part_number") or "")),
        (PROP_CANONICAL_KEY, str(identity.get("canonical_key") or "")),
    )
    result: list[dict[str, Any]] = []
    for name, value in values:
        if not value:
            raise FastenerCatalogError(
                f"Fastener BOM identity is missing {name}."
            )
        result.append(
            {
                "name": name,
                "property_type": "App::PropertyString",
                "kind": "string",
                "value": value,
            }
        )
    return result


def assembly_component_contract(
    shape: Any,
    identity: Mapping[str, Any],
) -> dict[str, Any]:
    """Describe one generated fastener as an Assembly source.

    This contract is derived from the exact generated BREP and canonical
    catalog identity in both the isolated worker and the host validator.
    """

    if str(identity.get("schema") or "") != COMPONENT_SCHEMA:
        raise FastenerCatalogError(
            "Assembly fastener identity has an unsupported component schema."
        )
    if shape is None or bool(shape.isNull()) or not bool(shape.isValid()):
        raise FastenerCatalogError(
            "Assembly fastener source must contain one valid generated BREP."
        )
    if len(shape.Solids) != 1:
        raise FastenerCatalogError(
            "Assembly fastener source must contain exactly one solid."
        )
    proxy = type("_FastenerShape", (), {"Shape": shape})()
    native_interfaces = _interfaces(
        proxy,
        str(identity["family"]),
        float(identity["nominal_diameter_mm"]),
        standard=str(identity["standard"]),
        length_mm=(
            float(identity["length_mm"])
            if identity.get("length_mm") is not None
            else None
        ),
    )
    published: dict[str, dict[str, Any]] = {}
    geometry_types = {
        "axis": "line",
        "plane": "plane",
        "cylinder": "cylinder",
    }
    for name, raw in dict(native_interfaces["interfaces"]).items():
        interface = dict(raw)
        kind = str(interface.get("kind") or "")
        geometry_type = geometry_types.get(kind)
        if geometry_type is None:
            continue
        published[name] = {
            "model_id": str(identity["canonical_key"]),
            "publication_name": name,
            "output_key": str(identity["canonical_key"]),
            "subelements": [],
            "geometry": [{"geometry_type": geometry_type}],
            "standard_frame": _interface_frame(interface),
        }
    if not {"axis", "thread_axis", "mounting_plane"} <= set(published):
        raise FastenerCatalogError(
            "Generated fastener is missing its required Assembly interfaces."
        )
    return {
        "label": str(identity["part_number"]),
        "type_id": "Part::FeaturePython",
        "source_kind": "standard_fastener",
        "transient_topology": True,
        # Catalog fasteners have a canonical local frame, so their component
        # origin is stable across regeneration and is safe for Assembly joints.
        # Their generated FaceN/EdgeN names remain transient and are still
        # rejected by the transient_topology guard in the Assembly worker.
        "requires_semantic_interfaces": False,
        "published_interfaces": published,
        "facts": {
            "shape_type": str(shape.ShapeType),
            "solids": len(shape.Solids),
            "shells": len(shape.Shells),
            "faces": len(shape.Faces),
            "wires": len(shape.Wires),
            "edges": len(shape.Edges),
            "vertices": len(shape.Vertexes),
        },
        "document_file_name": "",
        "bom_properties": fastener_bom_properties(identity),
    }


def _identity_from_object(obj: Any) -> dict[str, Any]:
    standard = canonical_standard(getattr(obj, "Type", ""))
    nominal_size = _catalog_token(
        getattr(obj, "Diameter", ""),
        _nominal_sizes(standard),
        name="Diameter",
    )
    options: dict[str, Any] = {}
    parameters = _standard_parameters(standard)
    for name, (requirement, property_name, kind) in _OPTION_PROPERTIES.items():
        if requirement not in parameters or not hasattr(obj, property_name):
            continue
        value = getattr(obj, property_name)
        if kind == "length":
            options[name] = float(value.Value)
        elif kind == "integer":
            options[name] = int(value)
        elif kind == "boolean":
            options[name] = bool(value)
        else:
            options[name] = str(value)
    return resolve_fastener(
        standard=standard,
        nominal_thread=nominal_size,
        length_mm=_active_length(obj),
        model_thread=bool(getattr(obj, "Thread", False)),
        left_handed=bool(getattr(obj, "LeftHanded", False)),
        options=options,
    )


def fastener_feature_identity(obj: Any) -> dict[str, Any]:
    """Return and verify the current catalog identity of a native feature."""

    if str(getattr(obj, PROP_SCHEMA, "") or "") != COMPONENT_SCHEMA:
        raise FastenerCatalogError(
            "object is not a SteveCAD standard-fastener feature."
        )
    identity = _identity_from_object(obj)
    stored_key = str(getattr(obj, PROP_CANONICAL_KEY, "") or "")
    if stored_key and stored_key != identity["canonical_key"]:
        raise FastenerCatalogError(
            "The fastener's editable parameters do not match its stored "
            "canonical identity; recompute the object before editing it."
        )
    return identity


def compatible_fastener_standards(obj: Any) -> list[str]:
    """List standards that can safely reuse this feature's native properties."""

    identity = fastener_feature_identity(obj)
    modules = _load_upstream()
    parameter_group = modules["FastenersCmd"].FSGetParams(identity["standard"])
    compatible = {
        str(standard)
        for standard in modules["ScrewMaker"].screwTables
        if modules["FastenersCmd"].FSGetParams(str(standard)) is parameter_group
    }
    compatible.add(str(identity["standard"]))
    return sorted(compatible)


def update_fastener_feature(
    obj: Any,
    *,
    standard: Any,
    nominal_thread: Any,
    length_mm: Any = None,
    model_thread: bool = False,
    left_handed: bool = False,
    options: Mapping[str, Any] | None = None,
    label: str | None = None,
    targeted_recompute: bool = False,
) -> dict[str, Any]:
    """Update one native feature without replacing its document identity.

    Standards may change only within the upstream generator's compatible
    property group. A caller that needs a different family must insert a new
    component, which avoids silently changing references to another kind of
    hardware.
    """

    if not isinstance(targeted_recompute, bool):
        raise FastenerCatalogError("targeted_recompute must be a boolean.")
    current = fastener_feature_identity(obj)
    previous_label = str(getattr(obj, "Label", "") or "")
    identity = resolve_fastener(
        standard=standard,
        nominal_thread=nominal_thread,
        length_mm=length_mm,
        model_thread=model_thread,
        left_handed=left_handed,
        options=options,
    )
    compatible = compatible_fastener_standards(obj)
    if identity["standard"] not in compatible:
        raise FastenerCatalogError(
            f"standard {identity['standard']!r} cannot replace "
            f"{current['standard']!r} in place because their native parameter "
            "contracts differ. Insert a new standard component instead. "
            f"Compatible standards: {compatible}."
        )
    proxy = getattr(obj, "Proxy", None)
    if not isinstance(proxy, SteveCADFastenerProxy):
        raise FastenerCatalogError(
            "object has no SteveCAD standard-fastener parametric proxy."
        )
    delegate = proxy._restore_delegate(obj)
    # The upstream generator caches its last-seen property values on the
    # Python proxy, but those Python fields are not part of FreeCAD's undo
    # journal. Rebase that cache from the exact live feature before applying
    # this controlled edit; otherwise an edit after Undo can compare against
    # future values and incorrectly enter its custom-length path.
    delegate.BackupObject(obj)
    if str(obj.Type) != str(identity["standard"]):
        obj.Type = compatible
        obj.Type = str(identity["standard"])
        delegate.VerifyMissingAttrs(obj, str(identity["standard"]))
        obj.Proxy = proxy
    diameter_values = list(_nominal_sizes(str(identity["standard"])))
    obj.Diameter = diameter_values
    obj.Diameter = str(identity["nominal_size"])
    for option_name, option_value in dict(identity["options"]).items():
        _set_object_option(obj, option_name, option_value)
    if identity["length_mm"] is not None:
        if isinstance(obj.Length, str):
            obj.Length = list(identity["allowed_length_tokens"])
            obj.Length = str(identity["length_token"])
        else:
            obj.Length = float(identity["length_mm"])
    if hasattr(obj, "LeftHanded"):
        obj.LeftHanded = bool(identity["left_handed"])
    if hasattr(obj, "Thread"):
        obj.Thread = bool(identity["model_thread"])
    proxy.standard = str(identity["standard"])
    if targeted_recompute:
        if obj.Document.recompute([obj], True, True) is False:
            raise FastenerCatalogError(
                "The edited standard fastener failed its targeted recompute."
            )
    else:
        obj.Document.recompute()
    observed = _identity_from_object(obj)
    if observed["canonical_key"] != identity["canonical_key"]:
        raise FastenerCatalogError(
            "The pinned generator changed the requested catalog identity "
            "during the in-place update."
        )
    _write_metadata(obj, observed)
    if label is not None:
        obj.Label = (
            _bounded_text(label, name="label")
            if str(label).strip()
            else str(observed["part_number"])
        )
    elif previous_label == str(current["part_number"]):
        obj.Label = str(observed["part_number"])
    return observed


def _write_metadata(obj: Any, identity: Mapping[str, Any]) -> None:
    previous_catalog_part_number = str(
        getattr(obj, PROP_CATALOG_PART_NUMBER, "") or ""
    )
    previous_part_number = str(getattr(obj, "PartNumber", "") or "")
    property_specs = (
        (PROP_SCHEMA, "App::PropertyString", "Standard-component schema."),
        (PROP_CATALOG, "App::PropertyString", "Authoritative catalog identity."),
        (
            PROP_CATALOG_VERSION,
            "App::PropertyString",
            "Catalog version used to resolve this component.",
        ),
        (
            PROP_GENERATOR_REVISION,
            "App::PropertyString",
            "Pinned geometry-generator revision.",
        ),
        (PROP_STANDARD, "App::PropertyString", "Published engineering standard."),
        (PROP_FAMILY, "App::PropertyString", "Standard-component family."),
        (
            PROP_NOMINAL_SIZE,
            "App::PropertyString",
            "Published nominal size or thread designation.",
        ),
        (
            PROP_NOMINAL_DIAMETER,
            "App::PropertyLength",
            "Resolved nominal diameter.",
        ),
        (PROP_LENGTH, "App::PropertyLength", "Resolved component length."),
        (
            PROP_CANONICAL_KEY,
            "App::PropertyString",
            "Stable catalog and parameter identity.",
        ),
        (
            PROP_CANONICAL_IDENTITY,
            "App::PropertyString",
            "Canonical standard-component definition.",
        ),
        (
            PROP_INTERFACES,
            "App::PropertyString",
            "Named standard-component connector frames.",
        ),
        (
            PROP_CATALOG_PART_NUMBER,
            "App::PropertyString",
            "Catalog-derived procurement identity.",
        ),
        (
            PROP_ERROR,
            "App::PropertyString",
            "Direct catalog or generator error from the last recompute.",
        ),
    )
    for name, type_id, description in property_specs:
        _ensure_property(obj, type_id, name, description)
    if "PartNumber" not in set(getattr(obj, "PropertiesList", []) or []):
        obj.addProperty(
            "App::PropertyString",
            "PartNumber",
            "BOM",
            "Procurement part number.",
        )
    if "Description" not in set(getattr(obj, "PropertiesList", []) or []):
        obj.addProperty(
            "App::PropertyString",
            "Description",
            "BOM",
            "Procurement description.",
        )
    _set_metadata(obj, PROP_SCHEMA, COMPONENT_SCHEMA)
    _set_metadata(obj, PROP_CATALOG, CATALOG_ID)
    _set_metadata(obj, PROP_CATALOG_VERSION, str(identity["catalog_version"]))
    _set_metadata(
        obj,
        PROP_GENERATOR_REVISION,
        str(identity["generator_revision"]),
    )
    _set_metadata(obj, PROP_STANDARD, str(identity["standard"]))
    _set_metadata(obj, PROP_FAMILY, str(identity["family"]))
    _set_metadata(obj, PROP_NOMINAL_SIZE, str(identity["nominal_size"]))
    _set_metadata(
        obj,
        PROP_NOMINAL_DIAMETER,
        float(identity["nominal_diameter_mm"]),
    )
    _set_metadata(
        obj,
        PROP_LENGTH,
        float(identity["length_mm"] or 0.0),
    )
    _set_metadata(obj, PROP_CANONICAL_KEY, str(identity["canonical_key"]))
    canonical = {
        key: value
        for key, value in identity.items()
        if key
        not in {
            "allowed_length_tokens",
            "description",
            "part_number",
        }
    }
    _set_metadata(
        obj,
        PROP_CANONICAL_IDENTITY,
        json.dumps(
            canonical,
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ),
    )
    _set_metadata(
        obj,
        PROP_INTERFACES,
        json.dumps(
            _interfaces(
                obj,
                str(identity["family"]),
                float(identity["nominal_diameter_mm"]),
                standard=str(identity["standard"]),
                length_mm=(
                    float(identity["length_mm"])
                    if identity.get("length_mm") is not None
                    else None
                ),
            ),
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ),
    )
    _set_metadata(
        obj,
        PROP_CATALOG_PART_NUMBER,
        str(identity["part_number"]),
    )
    if (
        not previous_part_number.strip()
        or previous_part_number == previous_catalog_part_number
    ):
        obj.PartNumber = str(identity["part_number"])
    if not str(getattr(obj, "Description", "") or "").strip():
        obj.Description = str(identity["description"])
    _set_metadata(obj, PROP_ERROR, "")


class SteveCADFastenerProxy:
    """Keep upstream parametric geometry and SteveCAD identity synchronized."""

    def __init__(self, obj: Any, standard: str, attach_to: Any = None) -> None:
        self.schema = COMPONENT_SCHEMA
        self.standard = str(standard)
        self.catalog_version = provenance()["version"]
        self.generator_revision = provenance()["revision"]
        self._delegate = None
        delegate_class = _load_upstream()["FastenersCmd"].FSScrewObject
        if "Type" not in set(getattr(obj, "PropertiesList", []) or []):
            probe = delegate_class.__new__(delegate_class)
            compatible = list(probe.GetCompatibleTypes(str(standard)))
            if str(standard) not in compatible:
                compatible.append(str(standard))
                compatible.sort()
            obj.addProperty(
                "App::PropertyEnumeration",
                "Type",
                "Parameters",
                "Published fastener standard.",
            )
            obj.Type = compatible
            obj.Type = str(standard)
        delegate = delegate_class(
            obj,
            standard,
            attach_to,
        )
        self._delegate = delegate
        obj.Proxy = self

    def _restore_delegate(self, obj: Any) -> Any:
        if self._delegate is not None:
            return self._delegate
        delegate_class = _load_upstream()["FastenersCmd"].FSScrewObject
        delegate = delegate_class.__new__(delegate_class)
        delegate.onDocumentRestored(obj)
        self._delegate = delegate
        obj.Proxy = self
        return delegate

    def execute(self, obj: Any) -> None:
        try:
            current = provenance()
            if (
                self.catalog_version
                and self.catalog_version != current["version"]
            ) or (
                self.generator_revision
                and self.generator_revision != current["revision"]
            ):
                raise FastenerCatalogError(
                    "This fastener was created with catalog "
                    f"{self.catalog_version or '<unknown>'} at generator "
                    f"{self.generator_revision or '<unknown>'}; this build contains "
                    f"{current['version']} at {current['revision']}. An explicit "
                    "catalog migration is required before recompute."
                )
            delegate = self._restore_delegate(obj)
            # Resolve before invoking upstream so it cannot silently replace an
            # invalid stored diameter, length, or variant with a nearby value.
            expected = _identity_from_object(obj)
            preserved_label = str(getattr(obj, "Label", "") or "")
            delegate.execute(obj)
            if preserved_label:
                obj.Label = preserved_label
            observed = _identity_from_object(obj)
            if observed["canonical_key"] != expected["canonical_key"]:
                raise FastenerCatalogError(
                    "The pinned generator changed the requested catalog identity "
                    "during recompute."
                )
            _write_metadata(obj, observed)
        except Exception as exc:
            _ensure_property(
                obj,
                "App::PropertyString",
                PROP_ERROR,
                "Direct catalog or generator error from the last recompute.",
            )
            _set_metadata(obj, PROP_ERROR, f"{type(exc).__name__}: {exc}")
            raise

    def onDocumentRestored(self, obj: Any) -> None:
        self._delegate = None
        self._restore_delegate(obj)

    def dumps(self) -> dict[str, str]:
        return {
            "schema": COMPONENT_SCHEMA,
            "standard": str(self.standard),
            "catalog_version": str(self.catalog_version),
            "generator_revision": str(self.generator_revision),
        }

    def loads(self, state: Any) -> None:
        data = dict(state) if isinstance(state, Mapping) else {}
        self.schema = str(data.get("schema") or COMPONENT_SCHEMA)
        self.standard = str(data.get("standard") or "")
        self.catalog_version = str(data.get("catalog_version") or "")
        self.generator_revision = str(data.get("generator_revision") or "")
        self._delegate = None


class SteveCADFastenerViewProvider:
    """Use the bundled standard's real Fasteners icon in the tree."""

    def __init__(self, view: Any) -> None:
        view.Proxy = self
        self.Object = view.Object

    def attach(self, view: Any) -> None:
        self.Object = view.Object

    def updateData(self, _obj: Any, _property: str) -> None:
        return

    def getDisplayModes(self, _view: Any) -> list[str]:
        return []

    def setDisplayMode(self, mode: str) -> str:
        return mode

    def onChanged(self, _view: Any, _property: str) -> None:
        return

    def getIcon(self) -> str:
        modules = _load_upstream()
        standard = str(getattr(self.Object, "Type", "ISO4017") or "ISO4017")
        icon_name = modules["FSAliases"].FSGetIconAlias(standard) + ".svg"
        path = Path(modules["FSutils"].iconPath) / icon_name
        if not path.is_file():
            path = Path(modules["FSutils"].iconPath) / "ISO4017.svg"
        return str(path)

    def dumps(self) -> None:
        return None

    def loads(self, _state: Any) -> None:
        return


def install_fastener_view_provider(obj: Any) -> None:
    view = getattr(obj, "ViewObject", None)
    if view is None:
        return
    current = getattr(view, "Proxy", None)
    if isinstance(current, SteveCADFastenerViewProvider):
        return
    SteveCADFastenerViewProvider(view)


def _set_object_option(obj: Any, name: str, value: Any) -> None:
    _requirement, property_name, kind = _OPTION_PROPERTIES[name]
    if not hasattr(obj, property_name):
        raise FastenerCatalogError(
            f"The generated {obj.Type} object has no {property_name} property."
        )
    if kind == "enumeration":
        allowed = _catalog_option_values(
            str(obj.Type),
            str(obj.Diameter),
            name,
        )
        setattr(obj, property_name, allowed)
    setattr(obj, property_name, value)


def create_fastener_feature(
    container: Any,
    *,
    standard: Any,
    nominal_thread: Any,
    length_mm: Any = None,
    model_thread: bool = False,
    left_handed: bool = False,
    options: Mapping[str, Any] | None = None,
    object_name: str = "StandardFastener",
    label: str = "",
    attach_to: Any = None,
    targeted_recompute: bool = False,
) -> tuple[Any, dict[str, Any]]:
    """Create one native upstream-backed parametric feature in a document/body."""

    if not isinstance(targeted_recompute, bool):
        raise FastenerCatalogError("targeted_recompute must be a boolean.")
    identity = resolve_fastener(
        standard=standard,
        nominal_thread=nominal_thread,
        length_mm=length_mm,
        model_thread=model_thread,
        left_handed=left_handed,
        options=options,
    )
    name = _bounded_text(object_name, name="object_name", maximum=128)
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        raise FastenerCatalogError(
            "object_name must be a valid FreeCAD object name."
        )
    is_body = hasattr(container, "newObject") and str(
        getattr(container, "TypeId", "")
    ) == "PartDesign::Body"
    if is_body:
        document = container.Document
    elif hasattr(container, "addObject"):
        document = container
    else:
        raise FastenerCatalogError(
            "container must be a FreeCAD document or Part Design Body."
        )
    obj = None
    try:
        if is_body:
            obj = container.newObject("PartDesign::FeaturePython", name)
        else:
            obj = container.addObject("Part::FeaturePython", name)
        if obj is None:
            raise FastenerCatalogError(
                "FreeCAD could not create the fastener feature."
            )
        SteveCADFastenerProxy(
            obj,
            str(identity["standard"]),
            attach_to,
        )
        obj.Diameter = str(identity["nominal_size"])
        for option_name, option_value in dict(identity["options"]).items():
            _set_object_option(obj, option_name, option_value)
        if identity["length_mm"] is not None:
            if not hasattr(obj, "Length"):
                raise FastenerCatalogError(
                    f"The generated {identity['standard']} object has no "
                    "Length property."
                )
            if isinstance(obj.Length, str):
                token = identity["length_token"]
                if token is None:
                    raise FastenerCatalogError(
                        f"The generated {identity['standard']} object requires a "
                        "catalog length token."
                    )
                obj.Length = list(identity["allowed_length_tokens"])
                obj.Length = str(token)
            else:
                obj.Length = float(identity["length_mm"])
        if bool(identity["left_handed"]):
            obj.LeftHanded = True
        if hasattr(obj, "Thread"):
            obj.Thread = bool(identity["model_thread"])
        if targeted_recompute:
            if document.recompute([obj], True, True) is False:
                raise FastenerCatalogError(
                    "The created standard fastener failed its targeted recompute."
                )
        else:
            document.recompute()
        shape = getattr(obj, "Shape", None)
        if (
            shape is None
            or shape.isNull()
            or not shape.isValid()
            or len(shape.Solids) != 1
        ):
            raise FastenerCatalogError(
                f"{identity['standard']} {identity['nominal_size']} did not "
                "generate one valid solid."
            )
        _write_metadata(obj, identity)
        if label:
            obj.Label = _bounded_text(label, name="label")
        else:
            obj.Label = str(identity["part_number"])
        install_fastener_view_provider(obj)
        return obj, identity
    except Exception:
        if obj is not None:
            try:
                if document.getObject(str(obj.Name)) is not None:
                    document.removeObject(str(obj.Name))
            except Exception:
                pass
        raise
