# SPDX-License-Identifier: LGPL-2.1-or-later
"""Drive the File > Open handlers for Fusion .f3d/.f3z and Siemens .jt."""

from __future__ import annotations

import binascii
import io
import os
import struct
import sys
import tempfile
import unittest
import zipfile
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

REPO = Path(__file__).resolve().parents[1]
IMPORT_DIR = REPO / "src" / "Mod" / "Import"
FIXTURE_DIR = Path(__file__).resolve().parent / "data" / "cad_import"

if str(IMPORT_DIR) not in sys.path:
    sys.path.insert(0, str(IMPORT_DIR))

import cad_geometry  # noqa: E402
import importFusion  # noqa: E402
import importJT  # noqa: E402


def _fixtures() -> dict:
    cube = cad_geometry.cube_triangles(10.0)
    f3d = FIXTURE_DIR / "cube.f3d"
    f3z = FIXTURE_DIR / "cube.f3z"
    # Real Siemens JT2Go example part (FreeCAD data/tests/Jt/Engine valve).
    # Must not be generated by importJT.write_jt_tessellation.
    jt = FIXTURE_DIR / "siemens_jt2go_valve.jt"
    missing = [path for path in (f3d, f3z, jt) if not path.is_file()]
    if missing:
        raise FileNotFoundError(
            "Missing committed CAD import fixture(s): "
            + ", ".join(str(path) for path in missing)
        )
    header = jt.read_bytes()[:12]
    if header != b"Version 8.0 ":
        raise RuntimeError(f"Unexpected JT header {header!r} in {jt}")
    return {"f3d": f3d, "f3z": f3z, "jt": jt, "cube": cube}


class ParseFixturesTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.fx = _fixtures()

    def test_filters_list_native_extensions(self):
        self.assertIn("*.f3d", importFusion.IMPORT_TYPE)
        self.assertIn("*.f3z", importFusion.IMPORT_TYPE)
        self.assertIn("*.jt", importJT.IMPORT_TYPE)
        init = (IMPORT_DIR / "Init.py").read_text(encoding="utf-8")
        self.assertIn("importFusion", init)
        self.assertIn("*.f3d", init)
        self.assertIn("*.f3z", init)
        self.assertIn("importJT", init)
        self.assertIn("*.jt", init)

    def test_f3d_mesh_roundtrip(self):
        groups = importFusion.read_fusion_meshes(str(self.fx["f3d"]))
        self.assertEqual(len(groups), 1)
        self.assertEqual(len(groups[0]), 12)
        self._assert_cube_bounds(groups[0])

    def test_f3z_contains_part_mesh(self):
        groups = importFusion.read_fusion_meshes(str(self.fx["f3z"]))
        self.assertGreaterEqual(len(groups), 1)
        self.assertEqual(len(groups[0]), 12)

    def test_fusion_archive_centimeters_are_converted_to_freecad_mm(self):
        import fusion_ogs

        one_cm = [
            ((0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
        ]
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "centimeter.f3d"
            world, mesh = fusion_ogs.pack_ogs_cache(one_cm)
            _write_fusion_archive(path, mesh, world=world)
            groups = importFusion.read_fusion_meshes(str(path))
        self.assertEqual(len(groups), 1)
        xs = [v[0] for triangle in groups[0] for v in triangle]
        ys = [v[1] for triangle in groups[0] for v in triangle]
        self.assertAlmostEqual(max(xs), 10.0, places=5)
        self.assertAlmostEqual(max(ys), 10.0, places=5)

    def test_position_only_fusion_mesh_is_not_misread_as_position_normal(self):
        triangles = [
            ((0.0, 0.0, 0.0), (10.0, 0.0, 0.0), (0.0, 10.0, 0.0)),
            ((0.0, 0.0, 5.0), (10.0, 0.0, 5.0), (0.0, 10.0, 5.0)),
        ]
        raw = b"".join(
            struct.pack("<fff", *vertex) for tri in triangles for vertex in tri
        )
        self.assertEqual(cad_geometry.parse_fusion_mesh(raw), triangles)

    def test_zstandard_method_93_fusion_archive(self):
        import fusion_ogs

        try:
            from backports.zstd import compress
        except ImportError:
            try:
                from compression.zstd import compress
            except ImportError as exc:
                self.skipTest(f"No Zstandard implementation available: {exc}")

        one_cm = [
            ((0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
        ]
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "zstandard.f3d"
            world, mesh = fusion_ogs.pack_ogs_cache(one_cm)
            members = {
                "Manifest.dat": b"FusionDocument",
                "FusionAssetName[Active]/OGS.BlobFolder/OGS/DefaultScene/world": world,
                "FusionAssetName[Active]/OGS.BlobFolder/OGS/DefaultScene/Fusion_mesh_000": mesh,
            }
            _write_method_93_archive(path, members, compress)
            groups = importFusion.read_fusion_meshes(str(path))
        self.assertEqual(len(groups), 1)
        self.assertAlmostEqual(max(v[0] for t in groups[0] for v in t), 10.0)

    def test_f3z_manifest_selects_only_the_root_design(self):
        root = io_bytes_f3d(cad_geometry.cube_triangles(10.0))
        referenced = io_bytes_f3d(_translated_cube(100.0))
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "assembly.f3z"
            with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
                archive.writestr("Manifest.json", b'{"root":"root.f3d"}')
                archive.writestr("root.f3d", root)
                archive.writestr("referenced.f3d", referenced)
            groups = importFusion.read_fusion_meshes(str(path))
        self.assertEqual(len(groups), 1)
        self._assert_cube_bounds(groups[0])

    def test_jt_toc_triangles(self):
        path = self.fx["jt"]
        self.assertEqual(path.name, "siemens_jt2go_valve.jt")
        tris = importJT.read_jt_triangles(str(path))
        self.assertEqual(len(tris), 284)
        self.assertTrue(importJT._plausible(tris))
        self.assertEqual(importJT._jt_length_scale_to_mm(path.read_bytes()), 25.4)
        xs = [v[0] for t in tris for v in t]
        self.assertAlmostEqual(min(xs), 71.5589457035, places=5)
        self.assertAlmostEqual(max(xs), 181.5588428497, places=5)

    def test_truncated_jt_bitstream_raises_instead_of_reading_forever(self):
        reader = importJT._BitReader([0x80000000])
        with self.assertRaises(EOFError):
            reader.read_u32(33)

    def test_invalid_jt_does_not_guess_geometry_from_arbitrary_floats(self):
        header = bytearray(b"Version 8.1 JT".ljust(80, b"\x00"))
        header.append(0)
        header.extend(struct.pack("<ii", 0, 0))
        header.extend(bytes(16))
        header.extend(b"\x00" * ((12 - len(header) % 12) % 12))
        for triangle in self.fx["cube"]:
            for vertex in triangle:
                header.extend(struct.pack("<fff", *vertex))
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "not-geometry.jt"
            path.write_bytes(header)
            self.assertEqual(importJT.read_jt_triangles(str(path)), [])

    def test_negative_jt_strip_indices_are_rejected(self):
        self.assertEqual(importJT._strips_to_triangles([0, 3], [-1, 0, 1]), [])

    def test_jt_explicit_units_are_scaled_to_freecad_mm(self):
        self.assertEqual(
            importJT._jt_length_scale_to_mm(
                b"JT_PROP_MEASUREMENT_UNITS\x00centimeters"
            ),
            10.0,
        )
        self.assertEqual(
            importJT._jt_length_scale_to_mm(
                "JT_PROP_MEASUREMENT_UNITS\x00inches".encode("utf-16-le")
            ),
            25.4,
        )

    def test_jt_mixed_units_and_transforms_are_rejected(self):
        with self.assertRaisesRegex(RuntimeError, "multiple model units"):
            importJT._jt_length_scale_to_mm(
                b"JT_PROP_MEASUREMENT_UNITS millimeters centimeters"
            )
        with self.assertRaisesRegex(RuntimeError, "transform"):
            importJT._validate_supported_jt_features(importJT._TRANSFORM_GUID)

    def _assert_cube_bounds(self, tris):
        xs = [v[0] for t in tris for v in t]
        ys = [v[1] for t in tris for v in t]
        zs = [v[2] for t in tris for v in t]
        self.assertAlmostEqual(min(xs), 0.0, places=5)
        self.assertAlmostEqual(max(xs), 10.0, places=5)
        self.assertAlmostEqual(min(ys), 0.0, places=5)
        self.assertAlmostEqual(max(ys), 10.0, places=5)
        self.assertAlmostEqual(min(zs), 0.0, places=5)
        self.assertAlmostEqual(max(zs), 10.0, places=5)


class FusionOgsTest(unittest.TestCase):
    def test_indexed_cache_splits_disconnected_bodies(self):
        import fusion_ogs

        triangles = cad_geometry.cube_triangles(1.0) + _translated_cube(3.0, size=1.0)
        world, mesh = fusion_ogs.pack_ogs_cache(triangles)
        groups = fusion_ogs.parse_ogs_cache(world, mesh)
        self.assertEqual(sorted(len(group) for group in groups), [12, 12])

    def test_repeated_coincident_geometry_is_deduplicated(self):
        import fusion_ogs

        cube = cad_geometry.cube_triangles(1.0)
        world, mesh = fusion_ogs.pack_ogs_cache(cube + cube, repeated_references=3)
        groups = fusion_ogs.parse_ogs_cache(world, mesh)
        self.assertEqual(len(groups), 1)
        self.assertEqual(len(groups[0]), 12)

    def test_unclaimed_or_overlapping_blob_bytes_are_rejected(self):
        import fusion_ogs

        world, mesh = fusion_ogs.pack_ogs_cache(cad_geometry.cube_triangles(1.0))
        with self.assertRaisesRegex(ValueError, "coverage"):
            fusion_ogs.parse_ogs_cache(world, mesh + b"unclaimed")

    def test_world_must_have_the_fusion_render_list_magic(self):
        import fusion_ogs

        with self.assertRaisesRegex(ValueError, "OGS world"):
            fusion_ogs.parse_ogs_cache(b"not a world", b"")


class OpenHandlersTest(unittest.TestCase):
    """Calls the same open()/insert() File > Open uses. Needs FreeCAD."""

    @classmethod
    def setUpClass(cls):
        try:
            import FreeCAD  # noqa: F401
            import Mesh  # noqa: F401
            import Part  # noqa: F401
        except ImportError as exc:
            raise unittest.SkipTest(f"FreeCAD not importable: {exc}") from exc
        cls.fx = _fixtures()

    def test_f3d_open_places_shape(self):
        self._assert_open(importFusion.open, self.fx["f3d"], expect_faces=12)

    def test_f3z_insert_places_shape(self):
        import FreeCAD

        doc = FreeCAD.newDocument("F3ZInsert")
        importFusion.insert(str(self.fx["f3z"]), doc.Name)
        self._assert_geometry(doc, expect_faces=12)

    def test_jt_open_places_mesh_or_shape(self):
        self.assertEqual(self.fx["jt"].name, "siemens_jt2go_valve.jt")
        self._assert_open(importJT.open, self.fx["jt"], expect_faces=None)

    def test_failed_open_does_not_leave_empty_document(self):
        import FreeCAD

        before = set(FreeCAD.listDocuments())
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "empty.jt"
            path.write_bytes(b"Version 8.1 JT".ljust(80, b"\x00") + bytes(40))
            with self.assertRaises(RuntimeError):
                importJT.open(str(path))
        self.assertEqual(set(FreeCAD.listDocuments()), before)

    def test_failed_fusion_open_does_not_leave_empty_document(self):
        import FreeCAD

        before = set(FreeCAD.listDocuments())
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "empty.f3d"
            with zipfile.ZipFile(path, "w") as archive:
                archive.writestr("Manifest.dat", b"FusionDocument")
            with self.assertRaises(RuntimeError):
                importFusion.open(str(path))
        self.assertEqual(set(FreeCAD.listDocuments()), before)

    @unittest.skipUnless(os.name == "nt", "Windows-only process behavior")
    def test_external_converter_is_launched_without_a_console_window(self):
        completed = SimpleNamespace(returncode=1, stdout=b"", stderr=b"")
        with mock.patch.dict(importJT.os.environ, {"STEVECAD_EXCHANGERCONV": ""}):
            with mock.patch.object(
                importJT.shutil, "which", return_value="ExchangerConv.exe"
            ):
                with mock.patch.object(
                    importJT.subprocess, "run", return_value=completed
                ) as run:
                    self.assertFalse(
                        importJT._try_cad_exchanger("part.jt", object(), "part")
                    )
        self.assertTrue(run.call_args_list)
        for call in run.call_args_list:
            self.assertEqual(
                call.kwargs.get("creationflags"), subprocess_create_no_window()
            )

    def test_external_converter_retries_share_one_timeout_budget(self):
        completed = SimpleNamespace(returncode=1, stdout=b"", stderr=b"")
        with mock.patch.dict(importJT.os.environ, {"STEVECAD_EXCHANGERCONV": ""}):
            with mock.patch.object(
                importJT.shutil, "which", return_value="ExchangerConv"
            ):
                with mock.patch.object(
                    importJT.time, "monotonic", side_effect=[100.0, 100.0, 221.0]
                ):
                    with mock.patch.object(
                        importJT.subprocess, "run", return_value=completed
                    ) as run:
                        self.assertFalse(
                            importJT._try_cad_exchanger("part.jt", object(), "part")
                        )
        self.assertEqual(run.call_count, 1)

    def _assert_open(self, opener, path, expect_faces):
        doc = opener(str(path))
        self.assertIsNotNone(doc)
        self._assert_geometry(doc, expect_faces=expect_faces)

    def _assert_geometry(self, doc, expect_faces):
        parts = [
            o
            for o in doc.Objects
            if hasattr(o, "Shape") and o.Shape and not o.Shape.isNull()
        ]
        meshes = [
            o
            for o in doc.Objects
            if hasattr(o, "Mesh") and o.Mesh and o.Mesh.CountFacets > 0
        ]
        self.assertTrue(parts or meshes, "open/insert produced no Shape or Mesh")
        self.assertFalse(
            parts and meshes, "import produced overlapping Shape and Mesh objects"
        )
        if parts:
            self.assertTrue(all(part.Shape.isValid() for part in parts))
            faces = sum(len(o.Shape.Faces) for o in parts)
            solids = sum(len(o.Shape.Solids) for o in parts)
            self.assertGreaterEqual(faces + solids, 1)
            if expect_faces is not None and faces:
                self.assertEqual(faces, expect_faces)
        if meshes:
            facets = sum(o.Mesh.CountFacets for o in meshes)
            self.assertGreaterEqual(facets, 1)
            if expect_faces is not None:
                self.assertEqual(facets, expect_faces)


def _write_fusion_archive(path: Path, mesh: bytes, world: bytes | None = None) -> None:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
        archive.writestr("Manifest.dat", b"FusionDocument")
        if world is not None:
            archive.writestr(
                "FusionAssetName[Active]/OGS.BlobFolder/OGS/DefaultScene/world",
                world,
            )
        archive.writestr(
            "FusionAssetName[Active]/OGS.BlobFolder/OGS/DefaultScene/Fusion_mesh_000",
            mesh,
        )


def io_bytes_f3d(triangles) -> bytes:
    buffer = io.BytesIO()
    importFusion.write_f3d_fp(buffer, triangles)
    return buffer.getvalue()


def _translated_cube(offset: float, size: float = 10.0):
    return [
        tuple((vertex[0] + offset, vertex[1], vertex[2]) for vertex in triangle)
        for triangle in cad_geometry.cube_triangles(size)
    ]


def _write_method_93_archive(path: Path, members: dict[str, bytes], compress) -> None:
    payload = bytearray()
    central = bytearray()
    for member, content in members.items():
        name = member.encode("utf-8")
        offset = len(payload)
        packed = compress(content)
        crc = binascii.crc32(content) & 0xFFFFFFFF
        payload.extend(
            struct.pack(
                "<IHHHHHIIIHH",
                0x04034B50,
                63,
                0x800,
                93,
                0,
                0,
                crc,
                len(packed),
                len(content),
                len(name),
                0,
            )
        )
        payload.extend(name)
        payload.extend(packed)
        central.extend(
            struct.pack(
                "<IHHHHHHIIIHHHHHII",
                0x02014B50,
                63,
                63,
                0x800,
                93,
                0,
                0,
                crc,
                len(packed),
                len(content),
                len(name),
                0,
                0,
                0,
                0,
                0,
                offset,
            )
        )
        central.extend(name)
    central_offset = len(payload)
    payload.extend(central)
    payload.extend(
        struct.pack(
            "<IHHHHIIH",
            0x06054B50,
            0,
            0,
            len(members),
            len(members),
            len(central),
            central_offset,
            0,
        )
    )
    path.write_bytes(payload)


def subprocess_create_no_window() -> int:
    import subprocess

    return subprocess.CREATE_NO_WINDOW


if __name__ == "__main__":
    unittest.main()
