#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PREFIX=${HERE}/usr
# export LD_LIBRARY_PATH=${HERE}/usr/lib${LD_LIBRARY_PATH:+':'}$LD_LIBRARY_PATH
export PYTHONHOME=${HERE}/usr
export PATH_TO_FREECAD_LIBDIR=${HERE}/usr/lib
# export QT_QPA_PLATFORM_PLUGIN_PATH=${HERE}/usr/plugins
# export QT_XKB_CONFIG_ROOT=${HERE}/usr/lib
export FONTCONFIG_FILE=/etc/fonts/fonts.conf
export FONTCONFIG_PATH=/etc/fonts

# Fix: Use X to run on Wayland
export QT_QPA_PLATFORM=xcb

# The AppImage bundles libdrm_amdgpu from its build environment. On current
# Arch/Mesa systems that copy can make Qt's GLX probe see no framebuffer
# configurations. Preload the host-matched library when AMD hardware is
# present; the loader then reuses it instead of the bundled copy.
drm_root=${STEVECAD_DRM_ROOT:-/sys/class/drm}
libdrm_amdgpu=${STEVECAD_LIBDRM_AMDGPU:-/usr/lib/libdrm_amdgpu.so.1}
for vendor_path in "$drm_root"/card*/device/vendor; do
    [ -r "$vendor_path" ] || continue
    if [ "$(cat "$vendor_path")" = "0x1002" ] && [ -r "$libdrm_amdgpu" ]; then
        LD_PRELOAD="$libdrm_amdgpu${LD_PRELOAD:+:$LD_PRELOAD}"
        export LD_PRELOAD
        break
    fi
done

# Show packages info if DEBUG env variable is set
if [ "$DEBUG" = 1 ]; then
    cat ${HERE}/packages.txt
fi

# SSL
# https://forum.freecad.org/viewtopic.php?f=4&t=34873&start=20#p327416
export SSL_CERT_FILE=$PREFIX/ssl/cacert.pem
# https://github.com/FreeCAD/FreeCAD-AppImage/pull/20
export GIT_SSL_CAINFO=$HERE/usr/ssl/cacert.pem

# Support for launching other applications (from /usr/bin)
# https://github.com/FreeCAD/FreeCAD-AppImage/issues/30
if [ ! -z "$1" ] && [ -e "$HERE/usr/bin/$1" ] ; then
    MAIN="$HERE/usr/bin/$1" ; shift
else
    MAIN="$HERE/usr/bin/freecad"
fi

exec "${MAIN}" "$@"
